<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-zh-CN.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ModelDocDuExtension.GetFirstToLastFeats 方法 </title><meta name="Language" content="zh-cn" /><meta name="System.Keywords" content="GetFirstToLastFeats 方法" /><meta name="System.Keywords" content="ModelDocDuExtension.GetFirstToLastFeats 方法" /><meta name="Microsoft.Help.F1" content="Du.SolidWorks.Extension.ModelDocDuExtension.GetFirstToLastFeats" /><meta name="Microsoft.Help.Id" content="M:Du.SolidWorks.Extension.ModelDocDuExtension.GetFirstToLastFeats(SolidWorks.Interop.sldworks.IModelDoc2,System.Boolean)" /><meta name="Description" content="按顺序遍历特征" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Du.SolidWorks.Extension" /><meta name="file" content="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats" /><meta name="guid" content="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Du.SolidWorks.Extension 帮助文件<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/7172b43d-676c-4d2f-a4aa-8af53c0cb2ec.htm" title="Du.SolidWorks.Extension 帮助文件" tocid="roottoc">Du.SolidWorks.Extension 帮助文件</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Du_SolidWorks_Extension.htm" title="Du.SolidWorks.Extension" tocid="N_Du_SolidWorks_Extension">Du.SolidWorks.Extension</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Du_SolidWorks_Extension_ModelDocDuExtension.htm" title="ModelDocDuExtension 类" tocid="T_Du_SolidWorks_Extension_ModelDocDuExtension">ModelDocDuExtension 类</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension.htm" title="ModelDocDuExtension 方法" tocid="Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension">ModelDocDuExtension 方法</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_AsAssemblyDoc.htm" title="AsAssemblyDoc 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_AsAssemblyDoc">AsAssemblyDoc 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_AsPartDoc.htm" title="AsPartDoc 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_AsPartDoc">AsPartDoc 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_CreateSketch.htm" title="CreateSketch 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_CreateSketch">CreateSketch 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_CurrentComp.htm" title="CurrentComp 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_CurrentComp">CurrentComp 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurationFromID.htm" title="GetConfigurationFromID 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurationFromID">GetConfigurationFromID 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurations.htm" title="GetConfigurations 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurations">GetConfigurations 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFeats.htm" title="GetFeats 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFeats">GetFeats 方法 </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats.htm" title="GetFirstToLastFeats 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats">GetFirstToLastFeats 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetGlobals.htm" title="GetGlobals 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetGlobals">GetGlobals 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetModelDispalyDimensions.htm" title="GetModelDispalyDimensions 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetModelDispalyDimensions">GetModelDispalyDimensions 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetObjectFromPersistReference.htm" title="GetObjectFromPersistReference 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetObjectFromPersistReference">GetObjectFromPersistReference 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPersistReference__1.htm" title="GetPersistReference(T) 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPersistReference__1">GetPersistReference(T) 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPlanes.htm" title="GetPlanes 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPlanes">GetPlanes 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetRayIntersections.htm" title="GetRayIntersections 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetRayIntersections">GetRayIntersections 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetSelectedObjectsFromModel.htm" title="GetSelectedObjectsFromModel 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetSelectedObjectsFromModel">GetSelectedObjectsFromModel 方法 </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx.htm" title="GetTypeEx 方法 " tocid="Overload_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx">GetTypeEx 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_IsSpecType.htm" title="IsSpecType 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_IsSpecType">IsSpecType 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_ScreenToView.htm" title="ScreenToView 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_ScreenToView">ScreenToView 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_TemSaveAsFor.htm" title="TemSaveAsFor 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_TemSaveAsFor">TemSaveAsFor 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_UIUpdateEnable.htm" title="UIUpdateEnable 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_UIUpdateEnable">UIUpdateEnable 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_Using.htm" title="Using 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_Using">Using 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_ViewToScreen.htm" title="ViewToScreen 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_ViewToScreen">ViewToScreen 方法 </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="点击或拖拽改变大小" title="点击或拖拽改变大小" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="点击或拖拽改变大小" title="点击或拖拽改变大小" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/Help.png" /></td><td class="titleColumn"><h1>ModelDocDuExtension<span id="LSTCE988D51_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTCE988D51_0?cpp=::|nu=.");</script>GetFirstToLastFeats 方法 </h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            按顺序遍历特征
            </div><p> </p>
        <strong>命名空间：</strong> 
     <a href="N_Du_SolidWorks_Extension.htm">Du.SolidWorks.Extension</a><br />
        <strong>程序集：</strong>
     Du.SolidWorks (在 Du.SolidWorks.dll 中) 版本：0.1.1.0 (0.1.1)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />语法</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="复制">复制</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">List</span>&lt;<span class="identifier">IFeature</span>&gt; <span class="identifier">GetFirstToLastFeats</span>(
	<span class="keyword">this</span> <span class="identifier">IModelDoc2</span> <span class="parameter">doc</span>,
	<span class="identifier">bool</span> <span class="parameter">TopOnly</span> = <span class="keyword">true</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve">&lt;<span class="identifier">ExtensionAttribute</span>&gt;
<span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">GetFirstToLastFeats</span> ( 
	<span class="parameter">doc</span> <span class="keyword">As</span> <span class="identifier">IModelDoc2</span>,
	Optional <span class="parameter">TopOnly</span> <span class="keyword">As</span> <span class="identifier">Boolean</span> = <span class="keyword">true</span>
) <span class="keyword">As</span> <span class="identifier">List</span>(<span class="keyword">Of</span> <span class="identifier">IFeature</span>)</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">参数</h4><dl><dt><span class="parameter">doc</span></dt><dd>类型：<span class="nolink">IModelDoc2</span><br /><p style="color: #dc143c; font-size: 9pt; font-weight: bold;">[缺少 "M:Du.SolidWorks.Extension.ModelDocDuExtension.GetFirstToLastFeats(SolidWorks.Interop.sldworks.IModelDoc2,System.Boolean)" 的 &lt;param name="doc"/&gt; 文档]</p></dd><dt><span class="parameter">TopOnly</span> (Optional)</dt><dd>类型：<span class="nolink">System<span id="LSTCE988D51_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTCE988D51_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Boolean</span><br /><p style="color: #dc143c; font-size: 9pt; font-weight: bold;">[缺少 "M:Du.SolidWorks.Extension.ModelDocDuExtension.GetFirstToLastFeats(SolidWorks.Interop.sldworks.IModelDoc2,System.Boolean)" 的 &lt;param name="TopOnly"/&gt; 文档]</p></dd></dl><h4 class="subHeading">返回值</h4>类型：<span class="nolink">List</span><span id="LSTCE988D51_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTCE988D51_2?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><span class="nolink">IFeature</span><span id="LSTCE988D51_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTCE988D51_3?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br /><p style="color: #dc143c; font-size: 9pt; font-weight: bold;">[缺少 "M:Du.SolidWorks.Extension.ModelDocDuExtension.GetFirstToLastFeats(SolidWorks.Interop.sldworks.IModelDoc2,System.Boolean)" 的 &lt;returns&gt; 文档]</p><h4 class="subHeading">备注</h4>在 Visual Basic 和 C# 中，这个方法可以当成为类型 <span class="nolink">IModelDoc2</span> 的实例方法来调用。在采用实例方法语法调用这个方法时，请省略第一个参数。请参考 <a href="https://docs.microsoft.com/dotnet/visual-basic/programming-guide/language-features/procedures/extension-methods" target="_blank">扩展方法 (Visual Basic)</a> 或 <a href="https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/extension-methods" target="_blank">扩展方法 (C# 编程指南)</a> 获取更多信息。</div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />参见</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">引用</h4><div class="seeAlsoStyle"><a href="T_Du_SolidWorks_Extension_ModelDocDuExtension.htm">ModelDocDuExtension 类
    </a></div><div class="seeAlsoStyle"><a href="N_Du_SolidWorks_Extension.htm">Du.SolidWorks.Extension 命名空间</a></div></div></div></div><div id="pageFooter" class="pageFooter"> </div></body></html>