<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-zh-CN.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Component2Extension 方法</title><meta name="Language" content="zh-cn" /><meta name="System.Keywords" content="Component2Extension 类, 方法" /><meta name="Microsoft.Help.Id" content="Methods.T:Du.SolidWorks.Extension.Component2Extension" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Du.SolidWorks.Extension" /><meta name="file" content="Methods_T_Du_SolidWorks_Extension_Component2Extension" /><meta name="guid" content="Methods_T_Du_SolidWorks_Extension_Component2Extension" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Du.SolidWorks.Extension 帮助文件<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/7172b43d-676c-4d2f-a4aa-8af53c0cb2ec.htm" title="Du.SolidWorks.Extension 帮助文件" tocid="roottoc">Du.SolidWorks.Extension 帮助文件</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Du_SolidWorks_Extension.htm" title="Du.SolidWorks.Extension" tocid="N_Du_SolidWorks_Extension">Du.SolidWorks.Extension</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Du_SolidWorks_Extension_Component2Extension.htm" title="Component2Extension 类" tocid="T_Du_SolidWorks_Extension_Component2Extension">Component2Extension 类</a></div><div class="toclevel1 current" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Du_SolidWorks_Extension_Component2Extension.htm" title="Component2Extension 方法" tocid="Methods_T_Du_SolidWorks_Extension_Component2Extension">Component2Extension 方法</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_Edit.htm" title="Edit 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_Edit">Edit 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_GetChildrenEx.htm" title="GetChildrenEx 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_GetChildrenEx">GetChildrenEx 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeatures.htm" title="GetCompTopFeatures 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeatures">GetCompTopFeatures 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeaturesWithTypeName.htm" title="GetCompTopFeaturesWithTypeName 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeaturesWithTypeName">GetCompTopFeaturesWithTypeName 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_GetCompType.htm" title="GetCompType 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_GetCompType">GetCompType 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_GetModelDoc2Ex.htm" title="GetModelDoc2Ex 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_GetModelDoc2Ex">GetModelDoc2Ex 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_GetPostion.htm" title="GetPostion 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_GetPostion">GetPostion 方法 </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Du_SolidWorks_Extension_Component2Extension_SelectFor.htm" title="SelectFor 方法 " tocid="Overload_Du_SolidWorks_Extension_Component2Extension_SelectFor">SelectFor 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_SetFixStatus.htm" title="SetFixStatus 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_SetFixStatus">SetFixStatus 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_TakeCompTopFeaturesWhile.htm" title="TakeCompTopFeaturesWhile 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_TakeCompTopFeaturesWhile">TakeCompTopFeaturesWhile 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_UsingAllBody.htm" title="UsingAllBody 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_UsingAllBody">UsingAllBody 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_UsingChildren.htm" title="UsingChildren 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_UsingChildren">UsingChildren 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_Component2Extension_UsingCompModelDoc2.htm" title="UsingCompModelDoc2 方法 " tocid="M_Du_SolidWorks_Extension_Component2Extension_UsingCompModelDoc2">UsingCompModelDoc2 方法 </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="点击或拖拽改变大小" title="点击或拖拽改变大小" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="点击或拖拽改变大小" title="点击或拖拽改变大小" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/Help.png" /></td><td class="titleColumn"><h1>Component2Extension 方法</h1></td></tr></table><span class="introStyle"></span> <p><a href="T_Du_SolidWorks_Extension_Component2Extension.htm">Component2Extension</a> 类型公开以下成员。</p><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID0RB')" onkeypress="SectionExpandCollapse_CheckKey('ID0RB', event)" tabindex="0"><img id="ID0RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />方法</span></div><div id="ID0RBSection" class="collapsibleSection"><table class="members" id="methodList"><tr><th class="iconColumn">
								 
							</th><th>名称</th><th>说明</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_Edit.htm">Edit</a></td><td><div class="summary">
            编辑零部件,自动区分装配体还是零件
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_GetChildrenEx.htm">GetChildrenEx</a></td><td><div class="summary">
            获取组件的子组件
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeatures.htm">GetCompTopFeatures</a></td><td><div class="summary">
            获取组件顶层的所有特征
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeaturesWithTypeName.htm">GetCompTopFeaturesWithTypeName</a></td><td><div class="summary">
            用类型名过滤特征--只获取第一级特征
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_GetCompType.htm">GetCompType</a></td><td><div class="summary">
            获取组件的类型
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_GetModelDoc2Ex.htm">GetModelDoc2Ex</a></td><td><div class="summary">
            直接返回转换类型的ModelDoc对象
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_GetPostion.htm">GetPostion</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_SelectFor.htm">SelectFor(Component2, Action, Boolean)</a></td><td><div class="summary">
            选择后执行特定动作
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_SelectFor_1.htm">SelectFor(Component2, Action<span id="LST14A8B645_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST14A8B645_0?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>Component2<span id="LST14A8B645_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST14A8B645_1?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>, Boolean)</a></td><td><div class="summary">
            选择后执行特定动作
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_SetFixStatus.htm">SetFixStatus</a></td><td><div class="summary">
            设置是否固定
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_TakeCompTopFeaturesWhile.htm">TakeCompTopFeaturesWhile</a></td><td><div class="summary">
            获取特定的特征
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_UsingAllBody.htm">UsingAllBody</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_UsingChildren.htm">UsingChildren</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_Component2Extension_UsingCompModelDoc2.htm">UsingCompModelDoc2</a></td><td /></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />参见</span></div><div id="ID1RBSection" class="collapsibleSection"><h4 class="subHeading">引用</h4><div class="seeAlsoStyle"><a href="T_Du_SolidWorks_Extension_Component2Extension.htm">Component2Extension 类
    </a></div><div class="seeAlsoStyle"><a href="N_Du_SolidWorks_Extension.htm">Du.SolidWorks.Extension 命名空间</a></div></div></div></div><div id="pageFooter" class="pageFooter"> </div></body></html>