<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-zh-CN.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ModelDocDuExtension 方法</title><meta name="Language" content="zh-cn" /><meta name="System.Keywords" content="ModelDocDuExtension 类, 方法" /><meta name="Microsoft.Help.Id" content="Methods.T:Du.SolidWorks.Extension.ModelDocDuExtension" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Du.SolidWorks.Extension" /><meta name="file" content="Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension" /><meta name="guid" content="Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Du.SolidWorks.Extension 帮助文件<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/7172b43d-676c-4d2f-a4aa-8af53c0cb2ec.htm" title="Du.SolidWorks.Extension 帮助文件" tocid="roottoc">Du.SolidWorks.Extension 帮助文件</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Du_SolidWorks_Extension.htm" title="Du.SolidWorks.Extension" tocid="N_Du_SolidWorks_Extension">Du.SolidWorks.Extension</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Du_SolidWorks_Extension_ModelDocDuExtension.htm" title="ModelDocDuExtension 类" tocid="T_Du_SolidWorks_Extension_ModelDocDuExtension">ModelDocDuExtension 类</a></div><div class="toclevel1 current" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension.htm" title="ModelDocDuExtension 方法" tocid="Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension">ModelDocDuExtension 方法</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_AsAssemblyDoc.htm" title="AsAssemblyDoc 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_AsAssemblyDoc">AsAssemblyDoc 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_AsPartDoc.htm" title="AsPartDoc 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_AsPartDoc">AsPartDoc 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_CreateSketch.htm" title="CreateSketch 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_CreateSketch">CreateSketch 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_CurrentComp.htm" title="CurrentComp 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_CurrentComp">CurrentComp 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurationFromID.htm" title="GetConfigurationFromID 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurationFromID">GetConfigurationFromID 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurations.htm" title="GetConfigurations 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurations">GetConfigurations 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFeats.htm" title="GetFeats 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFeats">GetFeats 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats.htm" title="GetFirstToLastFeats 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats">GetFirstToLastFeats 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetGlobals.htm" title="GetGlobals 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetGlobals">GetGlobals 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetModelDispalyDimensions.htm" title="GetModelDispalyDimensions 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetModelDispalyDimensions">GetModelDispalyDimensions 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetObjectFromPersistReference.htm" title="GetObjectFromPersistReference 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetObjectFromPersistReference">GetObjectFromPersistReference 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPersistReference__1.htm" title="GetPersistReference(T) 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPersistReference__1">GetPersistReference(T) 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPlanes.htm" title="GetPlanes 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPlanes">GetPlanes 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetRayIntersections.htm" title="GetRayIntersections 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetRayIntersections">GetRayIntersections 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetSelectedObjectsFromModel.htm" title="GetSelectedObjectsFromModel 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetSelectedObjectsFromModel">GetSelectedObjectsFromModel 方法 </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx.htm" title="GetTypeEx 方法 " tocid="Overload_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx">GetTypeEx 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_IsSpecType.htm" title="IsSpecType 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_IsSpecType">IsSpecType 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_ScreenToView.htm" title="ScreenToView 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_ScreenToView">ScreenToView 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_TemSaveAsFor.htm" title="TemSaveAsFor 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_TemSaveAsFor">TemSaveAsFor 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_UIUpdateEnable.htm" title="UIUpdateEnable 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_UIUpdateEnable">UIUpdateEnable 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_Using.htm" title="Using 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_Using">Using 方法 </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Du_SolidWorks_Extension_ModelDocDuExtension_ViewToScreen.htm" title="ViewToScreen 方法 " tocid="M_Du_SolidWorks_Extension_ModelDocDuExtension_ViewToScreen">ViewToScreen 方法 </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="点击或拖拽改变大小" title="点击或拖拽改变大小" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="点击或拖拽改变大小" title="点击或拖拽改变大小" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/Help.png" /></td><td class="titleColumn"><h1>ModelDocDuExtension 方法</h1></td></tr></table><span class="introStyle"></span> <p><a href="T_Du_SolidWorks_Extension_ModelDocDuExtension.htm">ModelDocDuExtension</a> 类型公开以下成员。</p><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID0RB')" onkeypress="SectionExpandCollapse_CheckKey('ID0RB', event)" tabindex="0"><img id="ID0RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />方法</span></div><div id="ID0RBSection" class="collapsibleSection"><table class="members" id="methodList"><tr><th class="iconColumn">
								 
							</th><th>名称</th><th>说明</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_AsAssemblyDoc.htm">AsAssemblyDoc</a></td><td><div class="summary">
            转换为装配体
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_AsPartDoc.htm">AsPartDoc</a></td><td><div class="summary">
            转换为零件文档
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_CreateSketch.htm">CreateSketch</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_CurrentComp.htm">CurrentComp</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurationFromID.htm">GetConfigurationFromID</a></td><td><div class="summary">
            Look-up a configuration based on it's ID
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurations.htm">GetConfigurations</a></td><td><div class="summary">
            Get all configurations
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFeats.htm">GetFeats</a></td><td><div class="summary">
            获取所有的某种类型的特征
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats.htm">GetFirstToLastFeats</a></td><td><div class="summary">
            按顺序遍历特征
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetGlobals.htm">GetGlobals</a></td><td> 
        <span><strong>已过时。</strong></span>
    <div class="summary">
            获取方程式中所有的全局变量变转换为字典
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetModelDispalyDimensions.htm">GetModelDispalyDimensions</a></td><td><div class="summary">
            获取所有的特征尺寸
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetObjectFromPersistReference.htm">GetObjectFromPersistReference</a></td><td><div class="summary">
            Get an entity from its persist id.
            
            Because we should use the same version of `GetPersistReference` and `GetObjectFromPersistReference` resp.
            and the persist reference is saved with the models we should never ever use another version of the two methods.
            For more details see http://help.solidworks.com/2016/english/api/sldworksapi/SolidWorks.interop.sldworks~SolidWorks.interop.sldworks.IModelDocExtension~GetPersistReference3.html#remarksSection
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPersistReference__1.htm">GetPersistReference<span id="LSTEDEFE5D_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTEDEFE5D_0?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>T<span id="LSTEDEFE5D_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTEDEFE5D_1?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script></a></td><td><div class="summary">
            获取实体PID
            
            Because we should use the same version of `GetPersistReference` and `GetObjectFromPersistReference` resp.
            and the persist reference is saved with the models we should never ever use another version of the two methods.
            For more details see http://help.solidworks.com/2016/english/api/sldworksapi/SolidWorks.interop.sldworks~SolidWorks.interop.sldworks.IModelDocExtension~GetPersistReference3.html#remarksSection
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPlanes.htm">GetPlanes</a></td><td><div class="summary">
            获取所有的基准面
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetRayIntersections.htm">GetRayIntersections</a></td><td><div class="summary">
            Doesn't work when intersecting with wire bodies. 
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetSelectedObjectsFromModel.htm">GetSelectedObjectsFromModel</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx.htm">GetTypeEx(AssemblyDoc)</a></td><td><div class="summary">
            获取文档类型
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx_1.htm">GetTypeEx(IModelDoc2)</a></td><td><div class="summary">
            获取文档类型
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_IsSpecType.htm">IsSpecType</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_ScreenToView.htm">ScreenToView</a></td><td><div class="summary">
            从一个给定的屏幕上的X,Y变换到视图模型中的点和方向
            From a given X,Y screen coordinate return the model
            coordinates and the direction of looking.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_TemSaveAsFor.htm">TemSaveAsFor</a></td><td><div class="summary">
            另存为并加载到内存,然后关闭源文档
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_UIUpdateEnable.htm">UIUpdateEnable</a></td><td /></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_Using.htm">Using</a></td><td><div class="summary">
            执行操作然后关闭文档
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="公共方法" title="公共方法" /><img src="../icons/static.gif" alt="静态成员" title="静态成员" /></td><td><a href="M_Du_SolidWorks_Extension_ModelDocDuExtension_ViewToScreen.htm">ViewToScreen</a></td><td><div class="summary">
            空间点变换到屏幕
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />参见</span></div><div id="ID1RBSection" class="collapsibleSection"><h4 class="subHeading">引用</h4><div class="seeAlsoStyle"><a href="T_Du_SolidWorks_Extension_ModelDocDuExtension.htm">ModelDocDuExtension 类
    </a></div><div class="seeAlsoStyle"><a href="N_Du_SolidWorks_Extension.htm">Du.SolidWorks.Extension 命名空间</a></div></div></div></div><div id="pageFooter" class="pageFooter"> </div></body></html>