["Du.SolidWorks.Extension 帮助文件 - Redirect\u0000index.html\u000018","Version 1.0.0.0\u0000html/d20b6f1c-5639-4419-a525-e5eaa8d5cee5.htm\u000042","Welcome to the Du.SolidWorks.Extension\u0000html/7172b43d-676c-4d2f-a4aa-8af53c0cb2ec.htm\u000058","Version History\u0000html/dcf0638a-bdef-45e0-9693-f7b98cbf947a.htm\u000072","FeatMgrFeatsNotFoundException 事件\u0000html/Events_T_Du_SolidWorks_Extension_FeatMgrFeatsNotFoundException.htm\u000030","RefAxisNotFoundException 事件\u0000html/Events_T_Du_SolidWorks_Extension_RefAxisNotFoundException.htm\u000030","Delat 字段\u0000html/Fields_T_Du_SolidWorks_Extension_Delat.htm\u000024","Du.SolidWorks.Extension 帮助文件 - Search\u0000search.html\u000013","DuMacroFeatBase(TMacroFeature, TData) 字段\u0000html/Fields_T_Du_SolidWorks_Extension_DuMacroFeatBase_2.htm\u000037","IPropertyManagerPage2Builder 字段\u0000html/Fields_T_Du_SolidWorks_Extension_IPropertyManagerPage2Builder.htm\u000024","PointParam 字段\u0000html/Fields_T_Du_SolidWorks_Extension_PointParam.htm\u000025","SelectionManagerExtensions 字段\u0000html/Fields_T_Du_SolidWorks_Extension_SelectionManagerExtensions.htm\u000025","MathUtil 字段\u0000html/Fields_T_Du_SolidWorks_Math_MathUtil.htm\u000027","FeatureTypeName 字段\u0000html/Fields_T_Du_SolidWorks_Extension_FeatureTypeName.htm\u000082","Delat._Vector 字段\u0000html/F_Du_SolidWorks_Extension_Delat__Vector.htm\u000075","FeatureTypeName.CoordSys 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_CoordSys.htm\u000075","FeatureTypeName.ExplodeLineProfileFeature 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_ExplodeLineProfileFeature.htm\u000075","FeatureTypeName.MacroFeature 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_MacroFeature.htm\u000075","DuMacroFeatBase(TMacroFeature, TData)._EditPage 字段\u0000html/F_Du_SolidWorks_Extension_DuMacroFeatBase_2__EditPage.htm\u000069","FeatureTypeName.Component2 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_Component2.htm\u000074","FeatureTypeName.MateGroup 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_MateGroup.htm\u000072","FeatureTypeName.InContextFeatHolder 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_InContextFeatHolder.htm\u000075","FeatureTypeName.MateCoincident 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_MateCoincident.htm\u000075","FeatureTypeName.OrignSys 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_OrignSys.htm\u000075","FeatureTypeName.RefAxis 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_RefAxis.htm\u000075","FeatureTypeName.MateInPlane 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_MateInPlane.htm\u000075","FeatureTypeName.ProfileFeature 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_ProfileFeature.htm\u000074","SWFile 字段\u0000html/Fields_T_Du_SolidWorks_Extension_SWFile.htm\u000047","IPropertyManagerPage2Builder.Page 字段\u0000html/F_Du_SolidWorks_Extension_IPropertyManagerPage2Builder_Page.htm\u000075","PointParam.param 字段\u0000html/F_Du_SolidWorks_Extension_PointParam_param.htm\u000075","FeatureTypeName.RefPlane 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_RefPlane.htm\u000075","PointParam.point 字段\u0000html/F_Du_SolidWorks_Extension_PointParam_point.htm\u000075","SelectionManagerExtensions.StartIndex 字段\u0000html/F_Du_SolidWorks_Extension_SelectionManagerExtensions_StartIndex.htm\u000083","SWFile.Assembly 字段\u0000html/F_Du_SolidWorks_Extension_SWFile_Assembly.htm\u000076","FeatureTypeName.Sketch 字段\u0000html/F_Du_SolidWorks_Extension_FeatureTypeName_Sketch.htm\u000074","SelectionManagerExtensions.AnyMark 字段\u0000html/F_Du_SolidWorks_Extension_SelectionManagerExtensions_AnyMark.htm\u000085","SWFile.Drawing 字段\u0000html/F_Du_SolidWorks_Extension_SWFile_Drawing.htm\u000076","SWFile.DrawingTemplate 字段\u0000html/F_Du_SolidWorks_Extension_SWFile_DrawingTemplate.htm\u000076","SWFile.Part 字段\u0000html/F_Du_SolidWorks_Extension_SWFile_Part.htm\u000076","SWFile.PartTempalte 字段\u0000html/F_Du_SolidWorks_Extension_SWFile_PartTempalte.htm\u000076","swSelectTypeName 字段\u0000html/Fields_T_Du_SolidWorks_Extension_swSelectTypeName.htm\u0000203","swSelectTypeName.swSelBODYFEATURES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelBODYFEATURES.htm\u000072","swSelectTypeName.swSelATTRIBUTES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelATTRIBUTES.htm\u000081","swSelectTypeName.swSelCENTERMARKS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelCENTERMARKS.htm\u000075","swSelectTypeName.swSelBREAKLINES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelBREAKLINES.htm\u000072","swSelectTypeName.swSelARROWS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelARROWS.htm\u000072","SWFile.AssemblyTempalte 字段\u0000html/F_Du_SolidWorks_Extension_SWFile_AssemblyTempalte.htm\u000076","swSelectTypeName.swSelCOMPONENTS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelCOMPONENTS.htm\u000072","swSelectTypeName.swSelCOMPPATTERN 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelCOMPPATTERN.htm\u000087","swSelectTypeName.swSelCTHREADS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelCTHREADS.htm\u000085","swSelectTypeName.swSelDATUMPLANES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDATUMPLANES.htm\u000081","swSelectTypeName.swSelDCABINETS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDCABINETS.htm\u000087","swSelectTypeName.swSelDATUMPOINTS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDATUMPOINTS.htm\u000083","swSelectTypeName.swSelCONFIGURATIONS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelCONFIGURATIONS.htm\u000075","swSelectTypeName.swSelDATUMAXES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDATUMAXES.htm\u000081","swSelectTypeName.swSelDETAILCIRCLES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDETAILCIRCLES.htm\u000074","swSelectTypeName.swSelDATUMTAGS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDATUMTAGS.htm\u000072","swSelectTypeName.swSelDTMTARGS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDTMTARGS.htm\u000072","swSelectTypeName.swSelDRAWINGVIEWS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDRAWINGVIEWS.htm\u000076","swSelectTypeName.swSelEXTSKETCHPOINTS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelEXTSKETCHPOINTS.htm\u000072","swSelectTypeName.swSelDIMENSIONS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelDIMENSIONS.htm\u000072","swSelectTypeName.swSelHELIX 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelHELIX.htm\u000077","swSelectTypeName.swSelEDGES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelEDGES.htm\u000076","swSelectTypeName.swSelINCONTEXTFEATS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelINCONTEXTFEATS.htm\u000087","swSelectTypeName.swSelEXPLSTEPS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelEXPLSTEPS.htm\u000087","swSelectTypeName.swSelINCONTEXTFEAT 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelINCONTEXTFEAT.htm\u000075","swSelectTypeName.swSelMATEGROUP 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelMATEGROUP.htm\u000075","swSelectTypeName.swSelEXPLVIEWS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelEXPLVIEWS.htm\u000087","swSelectTypeName.swSelEXTSKETCHSEGS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelEXTSKETCHSEGS.htm\u000072","swSelectTypeName.swSelMATEGROUPS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelMATEGROUPS.htm\u000087","swSelectTypeName.swSelFACES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelFACES.htm\u000076","swSelectTypeName.swSelMATES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelMATES.htm\u000073","swSelectTypeName.swSelGTOLS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelGTOLS.htm\u000072","swSelectTypeName.swSelOBJHANDLES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelOBJHANDLES.htm\u000072","swSelectTypeName.swSelNOTES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelNOTES.htm\u000072","swSelectTypeName.swSelREFERENCECURVES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelREFERENCECURVES.htm\u000073","swSelectTypeName.swSelPOINTREFS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelPOINTREFS.htm\u000087","swSelectTypeName.swSelSFSYMBOLS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSFSYMBOLS.htm\u000072","swSelectTypeName.swSelOLEITEMS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelOLEITEMS.htm\u000076","swSelectTypeName.swSelSKETCHPOINTS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSKETCHPOINTS.htm\u000076","swSelectTypeName.swSelREFSURFACES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelREFSURFACES.htm\u000075","swSelectTypeName.swSelREFCURVES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelREFCURVES.htm\u000073","swSelectTypeName.swSelSHEETS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSHEETS.htm\u000072","swSelectTypeName.swSelSKETCHTEXT 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSKETCHTEXT.htm\u000087","swSelectTypeName.swSelWELDS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelWELDS.htm\u000072","swSelectTypeName.swSelSILHOUETTES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSILHOUETTES.htm\u000073","swSelectTypeName.swSelVERTICES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelVERTICES.htm\u000076","MathUtil.Epsilon 字段\u0000html/F_Du_SolidWorks_Math_MathUtil_Epsilon.htm\u000087","swSelectTypeName.swSelSKETCHES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSKETCHES.htm\u000080","swSelectTypeName.swSelSKETCHSEGS 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSKETCHSEGS.htm\u000076","swSelectTypeName.swSelSECTIONLINES 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSECTIONLINES.htm\u000074","swSelectTypeName.swSelSECTIONTEXT 字段\u0000html/F_Du_SolidWorks_Extension_swSelectTypeName_swSelSECTIONTEXT.htm\u000077","General Error\u0000html/GeneralError.htm\u000034","MathUtil.Rad2Deg 字段\u0000html/F_Du_SolidWorks_Math_MathUtil_Rad2Deg.htm\u000070","SWFlyoutCommandAttribute 方法\u0000html/Methods_T_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute.htm\u000098","CustomPropertyModel 方法\u0000html/Methods_T_Du_SolidWorks_Extension_CustomPropertyModel.htm\u000084","BoxOrderAttribute 方法\u0000html/Methods_T_Du_SolidWorks_Attributes_BoxOrderAttribute.htm\u000098","MathUtil.ZeroTolerance 字段\u0000html/F_Du_SolidWorks_Math_MathUtil_ZeroTolerance.htm\u000085","Component2Extension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_Component2Extension.htm\u000064","ComWrapper 方法\u0000html/Methods_T_Du_SolidWorks_ComWrapper.htm\u000082","Delat 方法\u0000html/Methods_T_Du_SolidWorks_Extension_Delat.htm\u000086","CommandCollectionAttribute 方法\u0000html/Methods_T_Du_SolidWorks_Attributes_CommandCollectionAttribute.htm\u000098","CustomPropertyManagerExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_CustomPropertyManagerExtension.htm\u000061","EdgeExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_EdgeExtension.htm\u000027","DuMacroFeatBase(TMacroFeature, TData) 方法\u0000html/Methods_T_Du_SolidWorks_Extension_DuMacroFeatBase_2.htm\u0000100","AssemblyDocExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_AssemblyDocExtension.htm\u000069","EnumObjExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_EnumObjExtension.htm\u000026","EquationManagerExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_EquationManagerExtension.htm\u000056","BodyExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_BodyExtension.htm\u000048","Edge3 方法\u0000html/Methods_T_Du_SolidWorks_Extension_Edge3.htm\u000084","SWCommandAttribute 方法\u0000html/Methods_T_Du_SolidWorks_Attributes_SWCommandAttribute.htm\u000098","FaceExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_FaceExtension.htm\u000029","FeatMgrFeatsNotFoundException 方法\u0000html/Methods_T_Du_SolidWorks_Extension_FeatMgrFeatsNotFoundException.htm\u000098","FeatureManagerExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_FeatureManagerExtension.htm\u000028","IPropertyManagerPageSelectionboxExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_IPropertyManagerPageSelectionboxExtension.htm\u000028","MathTransformExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_MathTransformExtension.htm\u000032","FeatureTypeName 方法\u0000html/Methods_T_Du_SolidWorks_Extension_FeatureTypeName.htm\u000084","IPropertyManagerGroupBuilder 方法\u0000html/Methods_T_Du_SolidWorks_Extension_IPropertyManagerGroupBuilder.htm\u000086","Matrix4X4ExtensionsSw 方法\u0000html/Methods_T_Du_SolidWorks_Extension_Matrix4X4ExtensionsSw.htm\u000024","ModelerExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ModelerExtension.htm\u000085","ICurveExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ICurveExtension.htm\u000038","IPropertyManagerPageWindowFromHandleWrapper 方法\u0000html/Methods_T_Du_SolidWorks_Extension_IPropertyManagerPageWindowFromHandleWrapper.htm\u000086","ObjectId 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ObjectId.htm\u000084","IPropertyManagerPage2Builder 方法\u0000html/Methods_T_Du_SolidWorks_Extension_IPropertyManagerPage2Builder.htm\u000091","IFeatureExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_IFeatureExtension.htm\u000028","MacroFeatureDataExtension(TFeatComSerivce, TData) 方法\u0000html/Methods_T_Du_SolidWorks_Extension_MacroFeatureDataExtension_2.htm\u000094","ObjectSelection 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ObjectSelection.htm\u000086","PMPageControl 方法\u0000html/Methods_T_Du_SolidWorks_Extension_PMPageControl.htm\u000084","ModelDocDuExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension.htm\u0000237","IMacroFeatureDataExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_IMacroFeatureDataExtension.htm\u000046","OperationsResult 方法\u0000html/Methods_T_Du_SolidWorks_Extension_OperationsResult.htm\u000084","ManipulatorHandler 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ManipulatorHandler.htm\u000095","PMPageControlAttribute 方法\u0000html/Methods_T_Du_SolidWorks_Extension_PMPageControlAttribute.htm\u000098","PointParam 方法\u0000html/Methods_T_Du_SolidWorks_Extension_PointParam.htm\u000084","Range3Double 方法\u0000html/Methods_T_Du_SolidWorks_Extension_Range3Double.htm\u000084","RayIntersection 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection.htm\u000086","SelectionBoxAttribute 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SelectionBoxAttribute.htm\u000098","PropertyManagerPage2Extension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_PropertyManagerPage2Extension.htm\u000025","SelectionManagerExtensions 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SelectionManagerExtensions.htm\u000036","RefAxisExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_RefAxisExtension.htm\u000024","SelectionBoxExtensions 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SelectionBoxExtensions.htm\u000024","SwCalloutHandlerWrapper 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SwCalloutHandlerWrapper.htm\u000085","RefAxisNotFoundException 方法\u0000html/Methods_T_Du_SolidWorks_Extension_RefAxisNotFoundException.htm\u000098","SldWorksExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SldWorksExtension.htm\u000089","SelectionData 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SelectionData.htm\u0000169","RefPlaneExtesion 方法\u0000html/Methods_T_Du_SolidWorks_Extension_RefPlaneExtesion.htm\u000029","SurfaceExtensions 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SurfaceExtensions.htm\u000051","SwCalloutHandlerWrapperHelper 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SwCalloutHandlerWrapperHelper.htm\u000090","PropertyManagerPage2Handler9Wrapper 方法\u0000html/Methods_T_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper.htm\u0000121","SelectionDataExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SelectionDataExtension.htm\u000093","SWPath 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SWPath.htm\u0000103","PointUv 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SurfaceExtensions_PointUv.htm\u000086","ViewExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_ViewExtension.htm\u000031","swEqu 方法\u0000html/Methods_T_Du_SolidWorks_Extension_swEqu.htm\u000095","MathUtilityExtension 方法\u0000html/Methods_T_Du_SolidWorks_Math_MathUtilityExtension.htm\u000028","PropertyManagerPageGroupExtension 方法\u0000html/Methods_T_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension.htm\u000049","swSelectTypeName 方法\u0000html/Methods_T_Du_SolidWorks_Extension_swSelectTypeName.htm\u000085","GroupData 方法\u0000html/Methods_T_Du_SolidWorks_GroupData.htm\u000069","MathVectorExtension 方法\u0000html/Methods_T_Du_SolidWorks_Math_MathVectorExtension.htm\u000048","IFlyoutCommand 方法\u0000html/Methods_T_Du_SolidWorks_Interface_IFlyoutCommand.htm\u000024","TestObj 方法\u0000html/Methods_T_Du_SolidWorks_Extension_TestObj.htm\u000084","PointDirection3 方法\u0000html/Methods_T_Du_SolidWorks_Math_PointDirection3.htm\u000085","TriadManipulatorExtensions 方法\u0000html/Methods_T_Du_SolidWorks_Extension_TriadManipulatorExtensions.htm\u000025","SWFile 方法\u0000html/Methods_T_Du_SolidWorks_Extension_SWFile.htm\u000085","Vector2 方法\u0000html/Methods_T_Du_SolidWorks_Math_Vector2.htm\u0000134","ISWAddinCommand 方法\u0000html/Methods_T_Du_SolidWorks_ISWAddinCommand.htm\u000025","Vector3 方法\u0000html/Methods_T_Du_SolidWorks_Math_Vector3.htm\u0000183","ConvexHull2 方法\u0000html/Methods_T_Du_SolidWorks_Math_ConvexHull2.htm\u000085","BoxOrderAttribute 构造函数\u0000html/M_Du_SolidWorks_Attributes_BoxOrderAttribute__ctor.htm\u000058","doubleExtesnion 方法\u0000html/Methods_T_Du_SolidWorks_Math_doubleExtesnion.htm\u000024","MathPointExtension 方法\u0000html/Methods_T_Du_SolidWorks_Math_MathPointExtension.htm\u000042","CommandCollectionAttribute 构造函数\u0000html/M_Du_SolidWorks_Attributes_CommandCollectionAttribute__ctor.htm\u0000109","SWFlyoutCommandAttribute 构造函数\u0000html/M_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute__ctor.htm\u0000154","ComWrapper.WriteAllText 方法\u0000html/M_Du_SolidWorks_ComWrapper_WriteAllText.htm\u0000203","BodyExtension.Add 方法 (IEnumerable(IBody2))\u0000html/M_Du_SolidWorks_Extension_BodyExtension_Add_1.htm\u0000220","MathUtil 方法\u0000html/Methods_T_Du_SolidWorks_Math_MathUtil.htm\u000085","SWCommandAttribute 构造函数\u0000html/M_Du_SolidWorks_Attributes_SWCommandAttribute__ctor.htm\u0000145","ComWrapper.writeText 方法\u0000html/M_Du_SolidWorks_ComWrapper_writeText.htm\u0000157","BodyExtension.CopyTs 方法\u0000html/M_Du_SolidWorks_Extension_BodyExtension_CopyTs.htm\u0000182","Component2Extension.Edit 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_Edit.htm\u0000212","Component2Extension.SelectFor 方法 (Component2, Action(Component2), Boolean)\u0000html/M_Du_SolidWorks_Extension_Component2Extension_SelectFor_1.htm\u0000240","ComWrapper.GetComTypeFor(T) 方法\u0000html/M_Du_SolidWorks_ComWrapper_GetComTypeFor__1.htm\u0000198","BodyExtension.GetTess 方法\u0000html/M_Du_SolidWorks_Extension_BodyExtension_GetTess.htm\u0000191","Component2Extension.SetFixStatus 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_SetFixStatus.htm\u0000171","AssemblyDocExtension.AddAxisCoinMate(TAxisOne, TAxisTwo) 方法\u0000html/M_Du_SolidWorks_Extension_AssemblyDocExtension_AddAxisCoinMate__2.htm\u0000570","BodyExtension.OperationsTs 方法\u0000html/M_Du_SolidWorks_Extension_BodyExtension_OperationsTs.htm\u0000282","Component2Extension.TakeCompTopFeaturesWhile 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_TakeCompTopFeaturesWhile.htm\u0000262","AssemblyDocExtension.AddFaceCoinMate(TFaceOne, TFaceTwo) 方法\u0000html/M_Du_SolidWorks_Extension_AssemblyDocExtension_AddFaceCoinMate__2.htm\u0000434","ComWrapper.ObjectArrayToDispatchWrapper 方法\u0000html/M_Du_SolidWorks_ComWrapper_ObjectArrayToDispatchWrapper.htm\u0000177","Component2Extension.UsingAllBody 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_UsingAllBody.htm\u0000360","AssemblyDocExtension.AddFaceDisMate(TFaceOne, TFaceTwo) 方法\u0000html/M_Du_SolidWorks_Extension_AssemblyDocExtension_AddFaceDisMate__2.htm\u0000464","ComWrapper.ReadAllText 方法\u0000html/M_Du_SolidWorks_ComWrapper_ReadAllText.htm\u0000184","Component2Extension.UsingChildren 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_UsingChildren.htm\u0000228","Component2Extension.GetChildrenEx 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_GetChildrenEx.htm\u0000174","AssemblyDocExtension.UsingAllComponents 方法 (AssemblyDoc, Action(Component2), swDocumentTypes_e, Boolean)\u0000html/M_Du_SolidWorks_Extension_AssemblyDocExtension_UsingAllComponents.htm\u0000203","Component2Extension.GetCompTopFeatures 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeatures.htm\u0000174","Component2Extension.UsingCompModelDoc2 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_UsingCompModelDoc2.htm\u0000228","DuMacroFeatBase(TMacroFeature, TData).Edit 方法\u0000html/M_Du_SolidWorks_Extension_DuMacroFeatBase_2_Edit.htm\u0000258","Component2Extension.GetCompTopFeaturesWithTypeName 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_GetCompTopFeaturesWithTypeName.htm\u0000222","AssemblyDocExtension.UsingAllComponents 方法 (AssemblyDoc, Action(Component2), Boolean)\u0000html/M_Du_SolidWorks_Extension_AssemblyDocExtension_UsingAllComponents_1.htm\u0000183","DuMacroFeatBase(TMacroFeature, TData).Regenerate 方法\u0000html/M_Du_SolidWorks_Extension_DuMacroFeatBase_2_Regenerate.htm\u0000258","CustomPropertyManagerExtension.AddProperty 方法 (CustomPropertyManager, CustomPropertyModel, swCustomPropertyAddOption_e)\u0000html/M_Du_SolidWorks_Extension_CustomPropertyManagerExtension_AddProperty.htm\u0000298","Component2Extension.GetCompType 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_GetCompType.htm\u0000162","DuMacroFeatBase(TMacroFeature, TData).EditFeat 方法\u0000html/M_Du_SolidWorks_Extension_DuMacroFeatBase_2_EditFeat.htm\u0000251","BodyExtension.Add 方法 (IBody2, IBody2)\u0000html/M_Du_SolidWorks_Extension_BodyExtension_Add.htm\u0000244","Component2Extension.GetModelDoc2Ex 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_GetModelDoc2Ex.htm\u0000162","CustomPropertyManagerExtension.AddProperty 方法 (CustomPropertyManager, List(CustomPropertyModel), swCustomPropertyAddOption_e)\u0000html/M_Du_SolidWorks_Extension_CustomPropertyManagerExtension_AddProperty_1.htm\u0000291","EdgeExtension.GetEdge3 方法\u0000html/M_Du_SolidWorks_Extension_EdgeExtension_GetEdge3.htm\u0000162","DuMacroFeatBase(TMacroFeature, TData).GetPropertyPage 方法\u0000html/M_Du_SolidWorks_Extension_DuMacroFeatBase_2_GetPropertyPage.htm\u0000251","Component2Extension.GetPostion 方法\u0000html/M_Du_SolidWorks_Extension_Component2Extension_GetPostion.htm\u0000182","EdgeExtension.GetVectorLength 方法\u0000html/M_Du_SolidWorks_Extension_EdgeExtension_GetVectorLength.htm\u0000164","DuMacroFeatBase(TMacroFeature, TData).RebuildNotify 方法\u0000html/M_Du_SolidWorks_Extension_DuMacroFeatBase_2_RebuildNotify.htm\u0000251","DuMacroFeatBase(TMacroFeature, TData).Security 方法\u0000html/M_Du_SolidWorks_Extension_DuMacroFeatBase_2_Security.htm\u0000258","Component2Extension.SelectFor 方法 (Component2, Action, Boolean)\u0000html/M_Du_SolidWorks_Extension_Component2Extension_SelectFor.htm\u0000217","EnumObjExtension.CastObj(T) 方法\u0000html/M_Du_SolidWorks_Extension_EnumObjExtension_CastObj__1.htm\u0000219","DuMacroFeatBase(TMacroFeature, TData) 构造函数\u0000html/M_Du_SolidWorks_Extension_DuMacroFeatBase_2__ctor.htm\u000068","EnumObjExtension.SWToInt 方法\u0000html/M_Du_SolidWorks_Extension_EnumObjExtension_SWToInt.htm\u0000177","Edge3 构造函数\u0000html/M_Du_SolidWorks_Extension_Edge3__ctor.htm\u0000154","CustomPropertyManagerExtension.GetAllProperty 方法\u0000html/M_Du_SolidWorks_Extension_CustomPropertyManagerExtension_GetAllProperty.htm\u0000174","EquationManagerExtension.AddEqu 方法\u0000html/M_Du_SolidWorks_Extension_EquationManagerExtension_AddEqu.htm\u0000281","EquationManagerExtension.GetAllEqu 方法\u0000html/M_Du_SolidWorks_Extension_EquationManagerExtension_GetAllEqu.htm\u0000174","FaceExtension.GetDistance 方法\u0000html/M_Du_SolidWorks_Extension_FaceExtension_GetDistance.htm\u0000220","CustomPropertyManagerExtension.GetProperty 方法\u0000html/M_Du_SolidWorks_Extension_CustomPropertyManagerExtension_GetProperty.htm\u0000268","EquationManagerExtension.SetEqu 方法 (EquationMgr, Int32, String)\u0000html/M_Du_SolidWorks_Extension_EquationManagerExtension_SetEqu_1.htm\u0000238","EquationManagerExtension.GetEqu 方法\u0000html/M_Du_SolidWorks_Extension_EquationManagerExtension_GetEqu.htm\u0000208","FaceExtension.GetTessTrianglesAllowConversion 方法\u0000html/M_Du_SolidWorks_Extension_FaceExtension_GetTessTrianglesAllowConversion.htm\u0000192","CustomPropertyManagerExtension.SetProperty 方法 (CustomPropertyManager, List(CustomPropertyModel))\u0000html/M_Du_SolidWorks_Extension_CustomPropertyManagerExtension_SetProperty.htm\u0000184","EquationManagerExtension.SetEqu 方法 (EquationMgr, String, String)\u0000html/M_Du_SolidWorks_Extension_EquationManagerExtension_SetEqu_2.htm\u0000282","EquationManagerExtension.SetEqu 方法 (EquationMgr, Dictionary(Int32, String))\u0000html/M_Du_SolidWorks_Extension_EquationManagerExtension_SetEqu.htm\u0000266","FaceExtension.GetTessTrianglesNoConversion 方法\u0000html/M_Du_SolidWorks_Extension_FaceExtension_GetTessTrianglesNoConversion.htm\u0000192","CustomPropertyManagerExtension.SetProperty 方法 (CustomPropertyManager, String, String)\u0000html/M_Du_SolidWorks_Extension_CustomPropertyManagerExtension_SetProperty_1.htm\u0000209","EquationManagerExtension.SetGlobalEqu 方法\u0000html/M_Du_SolidWorks_Extension_EquationManagerExtension_SetGlobalEqu.htm\u0000216","FeatMgrFeatsNotFoundException 构造函数\u0000html/M_Du_SolidWorks_Extension_FeatMgrFeatsNotFoundException__ctor.htm\u000099","CustomPropertyModel 构造函数\u0000html/M_Du_SolidWorks_Extension_CustomPropertyModel__ctor.htm\u0000247","FaceExtension.GetBoxTs 方法\u0000html/M_Du_SolidWorks_Extension_FaceExtension_GetBoxTs.htm\u0000162","Delat.Length 方法\u0000html/M_Du_SolidWorks_Extension_Delat_Length.htm\u000095","FeatureManagerExtension.GetFeatureInsertError 方法\u0000html/M_Du_SolidWorks_Extension_FeatureManagerExtension_GetFeatureInsertError.htm\u0000345","Delat.Unit 方法\u0000html/M_Du_SolidWorks_Extension_Delat_Unit.htm\u000095","IMacroFeatureDataExtension.GetFeatureDataValues 方法\u0000html/M_Du_SolidWorks_Extension_IMacroFeatureDataExtension_GetFeatureDataValues.htm\u0000131","Delat 构造函数\u0000html/M_Du_SolidWorks_Extension_Delat__ctor.htm\u0000103","FeatureManagerExtension.GetFeaturesEx 方法\u0000html/M_Du_SolidWorks_Extension_FeatureManagerExtension_GetFeaturesEx.htm\u0000252","IPropertyManagerPage2Builder.CreateGroupBoxEx 方法\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPage2Builder_CreateGroupBoxEx.htm\u0000296","IPropertyManagerGroupBuilder.AddControlToBuilder(T) 方法\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerGroupBuilder_AddControlToBuilder__1.htm\u0000611","IMacroFeatureDataExtension.GetSelectedObjects 方法\u0000html/M_Du_SolidWorks_Extension_IMacroFeatureDataExtension_GetSelectedObjects.htm\u0000256","IPropertyManagerPage2Builder 构造函数\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPage2Builder__ctor.htm\u0000100","IPropertyManagerGroupBuilder 构造函数\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerGroupBuilder__ctor.htm\u0000100","IMacroFeatureDataExtension.Read(T) 方法\u0000html/M_Du_SolidWorks_Extension_IMacroFeatureDataExtension_Read__1.htm\u0000204","FeatureManagerExtension.InsertMacroFeature(TFeature) 方法\u0000html/M_Du_SolidWorks_Extension_FeatureManagerExtension_InsertMacroFeature__1.htm\u0000474","IPropertyManagerPage2Builder.AddSelectedObject 方法\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPage2Builder_AddSelectedObject.htm\u0000142","FeatureTypeName 构造函数\u0000html/M_Du_SolidWorks_Extension_FeatureTypeName__ctor.htm\u000058","IMacroFeatureDataExtension.Write 方法\u0000html/M_Du_SolidWorks_Extension_IMacroFeatureDataExtension_Write.htm\u0000179","IPropertyManagerPageSelectionboxExtension.SetSelectionbox 方法\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPageSelectionboxExtension_SetSelectionbox.htm\u0000341","ManipulatorHandler.OnHandleLmbSelected 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnHandleLmbSelected.htm\u0000148","ManipulatorHandler.OnStringValueChanged 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnStringValueChanged.htm\u0000256","IPropertyManagerPageWindowFromHandleWrapper.SetWindowHandlex64 方法\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPageWindowFromHandleWrapper_SetWindowHandlex64.htm\u0000146","IPropertyManagerPage2Builder.AddWPFUserControl 方法\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPage2Builder_AddWPFUserControl.htm\u0000505","ICurveExtension.ClosestPointOn 方法 (ICurve, Vector3)\u0000html/M_Du_SolidWorks_Extension_ICurveExtension_ClosestPointOn.htm\u0000247","ManipulatorHandler.OnHandleRmbSelected 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnHandleRmbSelected.htm\u0000169","ManipulatorHandler.OnUpdateDrag 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnUpdateDrag.htm\u0000219","IPropertyManagerPageWindowFromHandleWrapper 构造函数\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPageWindowFromHandleWrapper__ctor.htm\u0000100","Matrix4X4ExtensionsSw.ToSwTransform 方法\u0000html/M_Du_SolidWorks_Extension_Matrix4X4ExtensionsSw_ToSwTransform.htm\u0000245","ManipulatorHandler.OnHandleSelected 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnHandleSelected.htm\u0000169","ManipulatorHandler 构造函数\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler__ctor.htm\u000058","ModelDocDuExtension.AsAssemblyDoc 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_AsAssemblyDoc.htm\u0000162","ManipulatorHandler.OnItemSetFocus 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnItemSetFocus.htm\u0000169","MathTransformExtension.GetPostion 方法\u0000html/M_Du_SolidWorks_Extension_MathTransformExtension_GetPostion.htm\u0000162","ModelDocDuExtension.AsPartDoc 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_AsPartDoc.htm\u0000162","MathTransformExtension.GetXAxis 方法\u0000html/M_Du_SolidWorks_Extension_MathTransformExtension_GetXAxis.htm\u0000162","ModelDocDuExtension.CreateSketch 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_CreateSketch.htm\u0000182","MathTransformExtension.GetYAxis 方法\u0000html/M_Du_SolidWorks_Extension_MathTransformExtension_GetYAxis.htm\u0000162","MacroFeatureDataExtension(TFeatComSerivce, TData) 构造函数\u0000html/M_Du_SolidWorks_Extension_MacroFeatureDataExtension_2__ctor.htm\u000068","ModelDocDuExtension.CurrentComp 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_CurrentComp.htm\u0000182","MathTransformExtension.GetZAxis 方法\u0000html/M_Du_SolidWorks_Extension_MathTransformExtension_GetZAxis.htm\u0000162","ManipulatorHandler.OnDelete 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnDelete.htm\u0000148","ModelDocDuExtension.GetConfigurationFromID 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurationFromID.htm\u0000215","ManipulatorHandler.OnDirectionFlipped 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnDirectionFlipped.htm\u0000123","MathTransformExtension.ToMatrix4X4 方法\u0000html/M_Du_SolidWorks_Extension_MathTransformExtension_ToMatrix4X4.htm\u0000182","ModelDocDuExtension.GetConfigurations 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetConfigurations.htm\u0000176","ManipulatorHandler.OnDoubleValueChanged 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnDoubleValueChanged.htm\u0000256","ModelDocDuExtension.GetFeats 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFeats.htm\u0000174","ICurveExtension.ClosestPointOn 方法 (ICurve, Double, Double, Double)\u0000html/M_Du_SolidWorks_Extension_ICurveExtension_ClosestPointOn_1.htm\u0000349","ManipulatorHandler.OnEndDrag 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnEndDrag.htm\u0000169","IPropertyManagerPageWindowFromHandleWrapper.SetWindowHandle 方法\u0000html/M_Du_SolidWorks_Extension_IPropertyManagerPageWindowFromHandleWrapper_SetWindowHandle.htm\u0000146","ManipulatorHandler.OnEndNoDrag 方法\u0000html/M_Du_SolidWorks_Extension_ManipulatorHandler_OnEndNoDrag.htm\u0000169","ICurveExtension.CreateTrimmedCurve 方法\u0000html/M_Du_SolidWorks_Extension_ICurveExtension_CreateTrimmedCurve.htm\u0000313","ModelDocDuExtension.GetTypeEx 方法 (AssemblyDoc)\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx.htm\u0000167","PropertyManagerPage2Handler9Wrapper.AfterActivation 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_AfterActivation.htm\u000076","ModelDocDuExtension.ScreenToView 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_ScreenToView.htm\u0000339","ModelDocDuExtension.GetTypeEx 方法 (IModelDoc2)\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx_1.htm\u0000167","IFeatureExtension.GetDefinition(T) 方法\u0000html/M_Du_SolidWorks_Extension_IFeatureExtension_GetDefinition__1.htm\u0000226","ModelerExtension.CreateCone 方法\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateCone.htm\u0000230","PropertyManagerPage2Handler9Wrapper.AfterClose 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_AfterClose.htm\u000076","IFeatureExtension.GetDisplayDimensions 方法\u0000html/M_Du_SolidWorks_Extension_IFeatureExtension_GetDisplayDimensions.htm\u0000194","ModelerExtension.CreateCylinder 方法\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateCylinder.htm\u0000171","ModelDocDuExtension.TemSaveAsFor 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_TemSaveAsFor.htm\u0000266","IFeatureExtension.GetSpecFeatData(T) 方法\u0000html/M_Du_SolidWorks_Extension_IFeatureExtension_GetSpecFeatData__1.htm\u0000226","ModelDocDuExtension.UIUpdateEnable 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_UIUpdateEnable.htm\u0000201","ModelerExtension.CreateSphereBody 方法\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateSphereBody.htm\u0000294","IMacroFeatureDataExtension.GetFeatureDataNames 方法\u0000html/M_Du_SolidWorks_Extension_IMacroFeatureDataExtension_GetFeatureDataNames.htm\u000088","ModelerExtension.CreateTrimmedLine 方法 (IModeler, Edge3)\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateTrimmedLine.htm\u0000226","ModelDocDuExtension.Using 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_Using.htm\u0000259","IMacroFeatureDataExtension.GetFeatureDataTypes 方法\u0000html/M_Du_SolidWorks_Extension_IMacroFeatureDataExtension_GetFeatureDataTypes.htm\u000088","ModelerExtension.CreateTrimmedLine 方法 (IModeler, MathPoint, MathPoint)\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateTrimmedLine_1.htm\u0000182","ModelDocDuExtension.ViewToScreen 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_ViewToScreen.htm\u0000275","ModelDocDuExtension.IsSpecType 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_IsSpecType.htm\u0000237","ModelerExtension.CreateTrimmedLine 方法 (IModeler, MathUtility, Vector3, Vector3, Double)\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateTrimmedLine_2.htm\u0000227","ModelerExtension.CreateBodyFromCylTs 方法\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateBodyFromCylTs.htm\u0000213","PropertyManagerPage2Handler9Wrapper.OnActiveXControlCreated 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnActiveXControlCreated.htm\u0000194","ModelDocDuExtension.RayIntersection 构造函数\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection__ctor.htm\u0000345","ModelerExtension.InterpolatePointsToCurve 方法\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_InterpolatePointsToCurve.htm\u0000445","ModelerExtension.CreateBox 方法 (IModeler, Vector3, Vector3, Double, Double, Double)\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateBox.htm\u0000479","PropertyManagerPage2Handler9Wrapper.OnButtonPress 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnButtonPress.htm\u0000121","ModelDocDuExtension.GetFirstToLastFeats 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetFirstToLastFeats.htm\u0000230","PropertyManagerPage2Handler9Wrapper.OnCheckboxCheck 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnCheckboxCheck.htm\u0000167","ModelDocDuExtension.GetGlobals 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetGlobals.htm\u0000198","PropertyManagerPage2Handler9Wrapper.OnClose 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnClose.htm\u0000121","ModelDocDuExtension.GetModelDispalyDimensions 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetModelDispalyDimensions.htm\u0000249","PropertyManagerPage2Handler9Wrapper.OnComboboxEditChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnComboboxEditChanged.htm\u0000167","PropertyManagerPage2Handler9Wrapper.OnComboboxSelectionChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnComboboxSelectionChanged.htm\u0000167","ModelDocDuExtension.GetObjectFromPersistReference 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetObjectFromPersistReference.htm\u0000289","ObjectId 构造函数\u0000html/M_Du_SolidWorks_Extension_ObjectId__ctor.htm\u000058","ObjectSelection.TryGetT(T) 方法\u0000html/M_Du_SolidWorks_Extension_ObjectSelection_TryGetT__1.htm\u0000197","ModelDocDuExtension.GetPersistReference(T) 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPersistReference__1.htm\u0000325","ObjectSelection 构造函数\u0000html/M_Du_SolidWorks_Extension_ObjectSelection__ctor.htm\u0000247","ModelDocDuExtension.GetPlanes 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetPlanes.htm\u0000174","OperationsResult 构造函数\u0000html/M_Du_SolidWorks_Extension_OperationsResult__ctor.htm\u0000155","ModelDocDuExtension.GetRayIntersections 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetRayIntersections.htm\u0000434","PMPageControlAttribute 构造函数\u0000html/M_Du_SolidWorks_Extension_PMPageControlAttribute__ctor.htm\u0000142","ModelerExtension.CreateBox 方法 (IModeler, Double, Double, Double)\u0000html/M_Du_SolidWorks_Extension_ModelerExtension_CreateBox_1.htm\u0000323","PMPageControl 构造函数 (swPropertyManagerPageControlType_e)\u0000html/M_Du_SolidWorks_Extension_PMPageControl__ctor.htm\u0000105","ModelDocDuExtension.GetSelectedObjectsFromModel 方法\u0000html/M_Du_SolidWorks_Extension_ModelDocDuExtension_GetSelectedObjectsFromModel.htm\u0000194","PropertyManagerPage2Handler9Wrapper.OnNextPage 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnNextPage.htm\u000098","PropertyManagerPage2Handler9Wrapper.OnPopupMenuItem 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnPopupMenuItem.htm\u0000121","PMPageControl 构造函数 (Int32, String, String, swPropertyManagerPageControlType_e, swPropertyManagerPageControlLeftAlign_e, swAddControlOptions_e)\u0000html/M_Du_SolidWorks_Extension_PMPageControl__ctor_1.htm\u0000402","PropertyManagerPage2Handler9Wrapper.OnNumberboxChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnNumberboxChanged.htm\u0000167","PropertyManagerPage2Handler9Wrapper.OnPopupMenuItemUpdate 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnPopupMenuItemUpdate.htm\u0000173","PointParam 构造函数\u0000html/M_Du_SolidWorks_Extension_PointParam__ctor.htm\u0000154","PropertyManagerPage2Handler9Wrapper.OnNumberBoxTrackingCompleted 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnNumberBoxTrackingCompleted.htm\u0000167","PropertyManagerPage2Handler9Wrapper.OnPreview 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnPreview.htm\u000098","PropertyManagerPage2Handler9Wrapper.OnPreviousPage 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnPreviousPage.htm\u000098","PropertyManagerPage2Handler9Wrapper.OnOptionCheck 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnOptionCheck.htm\u0000121","PropertyManagerPage2Extension.CreateGroupBoxEx 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Extension_CreateGroupBoxEx.htm\u0000295","PropertyManagerPage2Handler9Wrapper.OnRedo 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnRedo.htm\u000076","PropertyManagerPage2Handler9Wrapper.OnSelectionboxListChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnSelectionboxListChanged.htm\u0000167","PropertyManagerPage2Handler9Wrapper.OnSelectionboxCalloutCreated 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnSelectionboxCalloutCreated.htm\u0000121","PropertyManagerPage2Handler9Wrapper.OnSelectionboxCalloutDestroyed 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnSelectionboxCalloutDestroyed.htm\u0000121","PropertyManagerPage2Handler9Wrapper.OnSliderPositionChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnSliderPositionChanged.htm\u0000167","PropertyManagerPage2Handler9Wrapper.OnSelectionboxFocusChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnSelectionboxFocusChanged.htm\u0000121","PropertyManagerPage2Handler9Wrapper.OnSliderTrackingCompleted 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnSliderTrackingCompleted.htm\u0000167","PropertyManagerPage2Handler9Wrapper.OnWindowFromHandleControlCreated 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnWindowFromHandleControlCreated.htm\u0000194","RefAxisExtension.GetEdge3 方法\u0000html/M_Du_SolidWorks_Extension_RefAxisExtension_GetEdge3.htm\u0000182","PropertyManagerPage2Handler9Wrapper.OnSubmitSelection 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnSubmitSelection.htm\u0000311","PropertyManagerPage2Handler9Wrapper 构造函数\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper__ctor.htm\u0000100","RefAxisNotFoundException 构造函数\u0000html/M_Du_SolidWorks_Extension_RefAxisNotFoundException__ctor.htm\u000099","PropertyManagerPageGroupExtension.CreateLabel 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateLabel.htm\u0000526","PropertyManagerPage2Handler9Wrapper.OnTabClicked 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnTabClicked.htm\u0000146","RefPlaneExtesion.GetPointDirection3 方法\u0000html/M_Du_SolidWorks_Extension_RefPlaneExtesion_GetPointDirection3.htm\u0000213","PropertyManagerPage2Handler9Wrapper.OnTextboxChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnTextboxChanged.htm\u0000167","PropertyManagerPageGroupExtension.AddControlEx(T) 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_AddControlEx__1.htm\u0000297","PropertyManagerPage2Handler9Wrapper.OnUndo 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnUndo.htm\u000076","RefPlaneExtesion.Normal 方法\u0000html/M_Du_SolidWorks_Extension_RefPlaneExtesion_Normal.htm\u0000219","PropertyManagerPageGroupExtension.CreateListBox 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateListBox.htm\u0000526","PropertyManagerPage2Handler9Wrapper.OnWhatsNew 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnWhatsNew.htm\u000076","RefPlaneExtesion.Origin 方法\u0000html/M_Du_SolidWorks_Extension_RefPlaneExtesion_Origin.htm\u0000219","PropertyManagerPageGroupExtension.AddControl(T) 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_AddControl__1.htm\u0000579","SelectionBoxAttribute 构造函数 (swSelectType_e[])\u0000html/M_Du_SolidWorks_Extension_SelectionBoxAttribute__ctor.htm\u0000117","PropertyManagerPageGroupExtension.CreateNumberBox 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateNumberBox.htm\u0000526","SelectionBoxAttribute 构造函数 (Double, swSelectType_e[])\u0000html/M_Du_SolidWorks_Extension_SelectionBoxAttribute__ctor_1.htm\u0000165","PropertyManagerPageGroupExtension.AddWPFUserControl 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_AddWPFUserControl.htm\u0000680","SelectionBoxExtensions.SetSelectionColor 方法\u0000html/M_Du_SolidWorks_Extension_SelectionBoxExtensions_SetSelectionColor.htm\u0000206","SelectionDataExtension.GetObjects 方法 (SelectionData, IModelDoc2)\u0000html/M_Du_SolidWorks_Extension_SelectionDataExtension_GetObjects.htm\u0000259","PropertyManagerPageGroupExtension.CreateOption 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateOption.htm\u0000526","PropertyManagerPageGroupExtension.CreateButton 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateButton.htm\u0000526","SelectionDataExtension.GetObjects(T) 方法 (SelectionData, IModelDoc2)\u0000html/M_Du_SolidWorks_Extension_SelectionDataExtension_GetObjects__1.htm\u0000340","PropertyManagerPageGroupExtension.CreateSelectionBox 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateSelectionBox.htm\u0000526","SelectionData 构造函数\u0000html/M_Du_SolidWorks_Extension_SelectionData__ctor.htm\u000058","PropertyManagerPageGroupExtension.CreateCheckBox 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateCheckBox.htm\u0000526","SelectionManagerExtensions.CreateCallOut 方法\u0000html/M_Du_SolidWorks_Extension_SelectionManagerExtensions_CreateCallOut.htm\u0000344","swEqu.SetName 方法\u0000html/M_Du_SolidWorks_Extension_swEqu_SetName.htm\u000098","PropertyManagerPageGroupExtension.CreateSlider 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateSlider.htm\u0000526","SldWorksExtension.UsingActiveDoc 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_UsingActiveDoc.htm\u0000201","PropertyManagerPageGroupExtension.CreateComboBox 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateComboBox.htm\u0000526","swEqu.SetValue 方法\u0000html/M_Du_SolidWorks_Extension_swEqu_SetValue.htm\u0000116","SelectionManagerExtensions.GetAllSelectedObjects 方法\u0000html/M_Du_SolidWorks_Extension_SelectionManagerExtensions_GetAllSelectedObjects.htm\u0000174","swEqu 构造函数\u0000html/M_Du_SolidWorks_Extension_swEqu__ctor.htm\u000058","SldWorksExtension.UsingOpenDoc 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_UsingOpenDoc.htm\u0000201","SelectionManagerExtensions.GetAllSelectedObjectsEx 方法\u0000html/M_Du_SolidWorks_Extension_SelectionManagerExtensions_GetAllSelectedObjectsEx.htm\u0000174","SWFile.IsPartOrAssembly 方法\u0000html/M_Du_SolidWorks_Extension_SWFile_IsPartOrAssembly.htm\u0000143","PropertyManagerPageGroupExtension.CreateTextBox 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension_CreateTextBox.htm\u0000526","SWFile 构造函数\u0000html/M_Du_SolidWorks_Extension_SWFile__ctor.htm\u000058","SurfaceExtensions.GetClosestPointOnTs 方法 (IFace2, Vector3)\u0000html/M_Du_SolidWorks_Extension_SurfaceExtensions_GetClosestPointOnTs.htm\u0000213","SelectionManagerExtensions.GetObjectSelections 方法\u0000html/M_Du_SolidWorks_Extension_SelectionManagerExtensions_GetObjectSelections.htm\u0000174","SWPath.CreateATemFilePath 方法\u0000html/M_Du_SolidWorks_Extension_SWPath_CreateATemFilePath.htm\u0000137","SurfaceExtensions.GetClosestPointOnTs 方法 (ISurface, Vector3)\u0000html/M_Du_SolidWorks_Extension_SurfaceExtensions_GetClosestPointOnTs_1.htm\u0000236","SelectionManagerExtensions.GetSelectedObjects 方法\u0000html/M_Du_SolidWorks_Extension_SelectionManagerExtensions_GetSelectedObjects.htm\u0000253","SWPath.GetFileType 方法\u0000html/M_Du_SolidWorks_Extension_SWPath_GetFileType.htm\u0000131","Range3Double 构造函数\u0000html/M_Du_SolidWorks_Extension_Range3Double__ctor.htm\u0000109","SWPath 构造函数\u0000html/M_Du_SolidWorks_Extension_SWPath__ctor.htm\u000058","SldWorksExtension.ActiveDocEx 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_ActiveDocEx.htm\u0000182","SurfaceExtensions.GetClosestPointOnTs 方法 (ISurface, Double[])\u0000html/M_Du_SolidWorks_Extension_SurfaceExtensions_GetClosestPointOnTs_2.htm\u0000255","swSelectTypeName.GetSelectedTypeName 方法\u0000html/M_Du_SolidWorks_Extension_swSelectTypeName_GetSelectedTypeName.htm\u0000146","SldWorksExtension.CreateDocument 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_CreateDocument.htm\u0000289","swSelectTypeName 构造函数\u0000html/M_Du_SolidWorks_Extension_swSelectTypeName__ctor.htm\u000058","SurfaceExtensions.PointAt 方法\u0000html/M_Du_SolidWorks_Extension_SurfaceExtensions_PointAt.htm\u0000282","TestObj 构造函数\u0000html/M_Du_SolidWorks_Extension_TestObj__ctor.htm\u000058","SldWorksExtension.FileType 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_FileType.htm\u0000230","SurfaceExtensions.PointUv 构造函数\u0000html/M_Du_SolidWorks_Extension_SurfaceExtensions_PointUv__ctor.htm\u0000303","SldWorksExtension.HasDocOpened 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_HasDocOpened.htm\u0000208","TriadManipulatorExtensions.CreateTranslationTransform 方法\u0000html/M_Du_SolidWorks_Extension_TriadManipulatorExtensions_CreateTranslationTransform.htm\u0000360","SwCalloutHandlerWrapperHelper.CreateWrapper 方法\u0000html/M_Du_SolidWorks_Extension_SwCalloutHandlerWrapperHelper_CreateWrapper.htm\u0000190","SwCalloutHandlerWrapperHelper 构造函数\u0000html/M_Du_SolidWorks_Extension_SwCalloutHandlerWrapperHelper__ctor.htm\u000058","SldWorksExtension.LoadIgesInvisible 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_LoadIgesInvisible.htm\u0000285","TriadManipulatorExtensions.Project 方法\u0000html/M_Du_SolidWorks_Extension_TriadManipulatorExtensions_Project.htm\u0000450","SldWorksExtension.NewPartOrAssembly 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_NewPartOrAssembly.htm\u0000187","SwCalloutHandlerWrapper.OnStringValueChanged 方法\u0000html/M_Du_SolidWorks_Extension_SwCalloutHandlerWrapper_OnStringValueChanged.htm\u0000246","ViewExtension.GetXAxis 方法\u0000html/M_Du_SolidWorks_Extension_ViewExtension_GetXAxis.htm\u0000213","SwCalloutHandlerWrapper 构造函数 (ISwCalloutHandler)\u0000html/M_Du_SolidWorks_Extension_SwCalloutHandlerWrapper__ctor.htm\u0000105","SldWorksExtension.OpenInvisibleDocClient 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_OpenInvisibleDocClient.htm\u0000268","SwCalloutHandlerWrapper 构造函数 (Func(ICallout, Int32, String, Boolean))\u0000html/M_Du_SolidWorks_Extension_SwCalloutHandlerWrapper__ctor_1.htm\u0000162","ViewExtension.GetYAxis 方法\u0000html/M_Du_SolidWorks_Extension_ViewExtension_GetYAxis.htm\u0000213","SldWorksExtension.OpenInvisibleReadOnly 方法\u0000html/M_Du_SolidWorks_Extension_SldWorksExtension_OpenInvisibleReadOnly.htm\u0000376","swEqu.SetEquationName 方法\u0000html/M_Du_SolidWorks_Extension_swEqu_SetEquationName.htm\u0000133","ViewExtension.GetZAxis 方法\u0000html/M_Du_SolidWorks_Extension_ViewExtension_GetZAxis.htm\u0000213","swEqu.SetEquationValue 方法\u0000html/M_Du_SolidWorks_Extension_swEqu_SetEquationValue.htm\u0000151","swEqu.SetGlobalName 方法\u0000html/M_Du_SolidWorks_Extension_swEqu_SetGlobalName.htm\u0000100","PropertyManagerPage2Handler9Wrapper.OnGainedFocus 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnGainedFocus.htm\u0000121","swEqu.SetGlobalValue 方法\u0000html/M_Du_SolidWorks_Extension_swEqu_SetGlobalValue.htm\u0000123","MathUtilityExtension.YAxis 方法\u0000html/M_Du_SolidWorks_Math_MathUtilityExtension_YAxis.htm\u0000182","PointDirection3 构造函数\u0000html/M_Du_SolidWorks_Math_PointDirection3__ctor.htm\u0000154","MathUtilityExtension.ZAxis 方法\u0000html/M_Du_SolidWorks_Math_MathUtilityExtension_ZAxis.htm\u0000182","Vector2.Add 方法\u0000html/M_Du_SolidWorks_Math_Vector2_Add.htm\u0000122","MathUtil.Clamp 方法\u0000html/M_Du_SolidWorks_Math_MathUtil_Clamp.htm\u0000239","Vector2.AngleD 方法 (Vector2)\u0000html/M_Du_SolidWorks_Math_Vector2_AngleD.htm\u0000136","Vector2.DistanceSquared 方法\u0000html/M_Du_SolidWorks_Math_Vector2_DistanceSquared.htm\u0000149","PropertyManagerPage2Handler9Wrapper.OnGroupCheck 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnGroupCheck.htm\u0000167","Vector2.Dot 方法\u0000html/M_Du_SolidWorks_Math_Vector2_Dot.htm\u0000129","PropertyManagerPage2Handler9Wrapper.OnGroupExpand 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnGroupExpand.htm\u0000167","MathUtil 构造函数\u0000html/M_Du_SolidWorks_Math_MathUtil__ctor.htm\u000058","Vector2.FromAngleRad 方法\u0000html/M_Du_SolidWorks_Math_Vector2_FromAngleRad.htm\u0000125","PropertyManagerPage2Handler9Wrapper.OnHelp 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnHelp.htm\u000098","MathVectorExtension.LengthOfProjectionXY 方法\u0000html/M_Du_SolidWorks_Math_MathVectorExtension_LengthOfProjectionXY.htm\u0000188","Vector2.Normalize 方法\u0000html/M_Du_SolidWorks_Math_Vector2_Normalize.htm\u0000137","Vector2.Round 方法\u0000html/M_Du_SolidWorks_Math_Vector2_Round.htm\u000098","PropertyManagerPage2Handler9Wrapper.OnKeystroke 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnKeystroke.htm\u0000302","MathVectorExtension.Project 方法\u0000html/M_Du_SolidWorks_Math_MathVectorExtension_Project.htm\u0000234","Vector2.Set 方法 (Vector2)\u0000html/M_Du_SolidWorks_Math_Vector2_Set.htm\u0000127","PropertyManagerPage2Handler9Wrapper.OnListboxRMBUp 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnListboxRMBUp.htm\u0000217","MathVectorExtension.ToVector3 方法\u0000html/M_Du_SolidWorks_Math_MathVectorExtension_ToVector3.htm\u0000182","Vector2.Set 方法 (Double, Double)\u0000html/M_Du_SolidWorks_Math_Vector2_Set_1.htm\u0000167","PropertyManagerPage2Handler9Wrapper.OnListboxSelectionChanged 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnListboxSelectionChanged.htm\u0000167","PointDirection3.Transform 方法\u0000html/M_Du_SolidWorks_Math_PointDirection3_Transform.htm\u0000201","PropertyManagerPage2Handler9Wrapper.OnLostFocus 方法\u0000html/M_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper_OnLostFocus.htm\u0000121","Du.SolidWorks 命名空间\u0000html/N_Du_SolidWorks.htm\u000040","Vector2 构造函数\u0000html/M_Du_SolidWorks_Math_Vector2__ctor.htm\u0000142","CustomPropertyManagerExtension.AddProperty 方法\u0000html/Overload_Du_SolidWorks_Extension_CustomPropertyManagerExtension_AddProperty.htm\u000039","Vector3.Cross 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Cross_2.htm\u0000160","Vector3.IsSameDirection 方法\u0000html/M_Du_SolidWorks_Math_Vector3_IsSameDirection.htm\u0000129","Du.SolidWorks.Attributes 命名空间\u0000html/N_Du_SolidWorks_Attributes.htm\u000033","CustomPropertyManagerExtension.SetProperty 方法\u0000html/Overload_Du_SolidWorks_Extension_CustomPropertyManagerExtension_SetProperty.htm\u000037","Vector3.Add 方法\u0000html/M_Du_SolidWorks_Math_Vector3_Add.htm\u0000149","Vector3.Normalize 方法\u0000html/M_Du_SolidWorks_Math_Vector3_Normalize.htm\u0000155","EquationManagerExtension.SetEqu 方法\u0000html/Overload_Du_SolidWorks_Extension_EquationManagerExtension_SetEqu.htm\u000046","Vector3.Distance 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Distance.htm\u0000154","Vector3.AngleD 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_AngleD.htm\u0000109","Vector3.Orthogonal 方法\u0000html/M_Du_SolidWorks_Math_Vector3_Orthogonal.htm\u0000110","ICurveExtension.ClosestPointOn 方法\u0000html/Overload_Du_SolidWorks_Extension_ICurveExtension_ClosestPointOn.htm\u000035","ModelDocDuExtension.GetTypeEx 方法\u0000html/Overload_Du_SolidWorks_Extension_ModelDocDuExtension_GetTypeEx.htm\u000029","Vector3.ParaWithVec 方法\u0000html/M_Du_SolidWorks_Math_Vector3_ParaWithVec.htm\u0000130","Vector3.DistanceSquared 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_DistanceSquared.htm\u0000154","ModelerExtension.CreateBox 方法\u0000html/Overload_Du_SolidWorks_Extension_ModelerExtension_CreateBox.htm\u000045","Vector3.AngleD 方法 (Vector3, Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_AngleD_1.htm\u0000194","Du.SolidWorks.Extension 命名空间\u0000html/N_Du_SolidWorks_Extension.htm\u0000252","Vector3.Round 方法\u0000html/M_Du_SolidWorks_Math_Vector3_Round.htm\u0000116","Vector3.DistanceSquared 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_DistanceSquared_1.htm\u0000160","Du.SolidWorks.Interface 命名空间\u0000html/N_Du_SolidWorks_Interface.htm\u000028","ModelerExtension.CreateTrimmedLine 方法\u0000html/Overload_Du_SolidWorks_Extension_ModelerExtension_CreateTrimmedLine.htm\u000050","Vector3.AngleR 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_AngleR.htm\u0000136","Vector3.Scale 方法\u0000html/M_Du_SolidWorks_Math_Vector3_Scale.htm\u0000141","Du.SolidWorks.Math 命名空间\u0000html/N_Du_SolidWorks_Math.htm\u000039","PMPageControl 构造函数\u0000html/Overload_Du_SolidWorks_Extension_PMPageControl__ctor.htm\u000042","Vector3.Distance 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Distance_1.htm\u0000160","Vector3.AngleR 方法 (Vector3, Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_AngleR_1.htm\u0000194","Vector3.Set 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Set.htm\u0000127","AssemblyDocExtension.UsingAllComponents 方法\u0000html/Overload_Du_SolidWorks_Extension_AssemblyDocExtension_UsingAllComponents.htm\u000053","Vector3.Dot 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Dot.htm\u0000154","Vector2.Subtract 方法\u0000html/M_Du_SolidWorks_Math_Vector2_Subtract.htm\u0000122","BodyExtension.Add 方法\u0000html/Overload_Du_SolidWorks_Extension_BodyExtension_Add.htm\u000031","Vector3.Cross 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Cross.htm\u0000154","Component2Extension.SelectFor 方法\u0000html/Overload_Du_SolidWorks_Extension_Component2Extension_SelectFor.htm\u000039","ViewExtension.GetZAxisVec 方法\u0000html/M_Du_SolidWorks_Extension_ViewExtension_GetZAxisVec.htm\u0000213","Vector3.Dot 方法 (Vector3, Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Dot_1.htm\u0000216","Vector3.Cross 方法 (Vector3, Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Cross_1.htm\u0000216","IFlyoutCommand.Execute 方法\u0000html/M_Du_SolidWorks_Interface_IFlyoutCommand_Execute.htm\u0000114","Vector3.Dot 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_Dot_2.htm\u0000160","Vector2.AngleD 方法 (Vector2, Vector2)\u0000html/M_Du_SolidWorks_Math_Vector2_AngleD_1.htm\u0000194","Vector3 构造函数\u0000html/Overload_Du_SolidWorks_Math_Vector3__ctor.htm\u000038","ISWAddinCommand.AddFlyoutCommand 方法\u0000html/M_Du_SolidWorks_ISWAddinCommand_AddFlyoutCommand.htm\u0000414","SelectionBoxAttribute 构造函数\u0000html/Overload_Du_SolidWorks_Extension_SelectionBoxAttribute__ctor.htm\u000037","Vector2.AngleR 方法 (Vector2)\u0000html/M_Du_SolidWorks_Math_Vector2_AngleR.htm\u0000136","Page Not Found\u0000html/PageNotFound.htm\u000068","BoxOrderAttribute 属性\u0000html/Properties_T_Du_SolidWorks_Attributes_BoxOrderAttribute.htm\u000031","SelectionDataExtension.GetObjects 方法\u0000html/Overload_Du_SolidWorks_Extension_SelectionDataExtension_GetObjects.htm\u000094","Vector3.Set 方法 (Double, Double, Double)\u0000html/M_Du_SolidWorks_Math_Vector3_Set_1.htm\u0000217","CommandCollectionAttribute 属性\u0000html/Properties_T_Du_SolidWorks_Attributes_CommandCollectionAttribute.htm\u000031","Vector3.ToDoubles 方法\u0000html/M_Du_SolidWorks_Math_Vector3_ToDoubles.htm\u0000101","Vector2.AngleR 方法 (Vector2, Vector2)\u0000html/M_Du_SolidWorks_Math_Vector2_AngleR_1.htm\u0000194","SWCommandAttribute 属性\u0000html/Properties_T_Du_SolidWorks_Attributes_SWCommandAttribute.htm\u000053","ISWAddinCommand.AddSWCommand 方法\u0000html/M_Du_SolidWorks_ISWAddinCommand_AddSWCommand.htm\u0000627","Vector3.ToSwMathPoint 方法\u0000html/M_Du_SolidWorks_Math_Vector3_ToSwMathPoint.htm\u0000156","SWFlyoutCommandAttribute 属性\u0000html/Properties_T_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute.htm\u000037","Vector2.Cross 方法\u0000html/M_Du_SolidWorks_Math_Vector2_Cross.htm\u0000129","CustomPropertyModel 属性\u0000html/Properties_T_Du_SolidWorks_Extension_CustomPropertyModel.htm\u000033","Vector3.ToSwMathVector 方法\u0000html/M_Du_SolidWorks_Math_Vector3_ToSwMathVector.htm\u0000156","Vector2.Distance 方法\u0000html/M_Du_SolidWorks_Math_Vector2_Distance.htm\u0000149","DuMacroFeatBase(TMacroFeature, TData) 属性\u0000html/Properties_T_Du_SolidWorks_Extension_DuMacroFeatBase_2.htm\u000035","Vector3.Unit 方法\u0000html/M_Du_SolidWorks_Math_Vector3_Unit.htm\u0000155","ISWAddinCommand.CreatSWFlyoutGroup 方法\u0000html/M_Du_SolidWorks_ISWAddinCommand_CreatSWFlyoutGroup.htm\u0000606","SurfaceExtensions.GetClosestPointOnTs 方法\u0000html/Overload_Du_SolidWorks_Extension_SurfaceExtensions_GetClosestPointOnTs.htm\u000048","Vector3.UnitCross 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_UnitCross.htm\u0000134","ConvexHull2.GetConvexHull 方法\u0000html/M_Du_SolidWorks_Math_ConvexHull2_GetConvexHull.htm\u0000107","SwCalloutHandlerWrapper 构造函数\u0000html/Overload_Du_SolidWorks_Extension_SwCalloutHandlerWrapper__ctor.htm\u000040","Vector3.UnitCross 方法 (Vector3)\u0000html/M_Du_SolidWorks_Math_Vector3_UnitCross_1.htm\u0000139","MathPointExtension.SubtractTs 方法\u0000html/Overload_Du_SolidWorks_Math_MathPointExtension_SubtractTs.htm\u000031","Vector2.AngleD 方法\u0000html/Overload_Du_SolidWorks_Math_Vector2_AngleD.htm\u000035","ConvexHull2 构造函数\u0000html/M_Du_SolidWorks_Math_ConvexHull2__ctor.htm\u0000183","Vector3 构造函数 (Double, Double, Double)\u0000html/M_Du_SolidWorks_Math_Vector3__ctor.htm\u0000198","Vector2.AngleR 方法\u0000html/Overload_Du_SolidWorks_Math_Vector2_AngleR.htm\u000035","Vector2.Set 方法\u0000html/Overload_Du_SolidWorks_Math_Vector2_Set.htm\u000029","doubleExtesnion.ToVector3 方法\u0000html/M_Du_SolidWorks_Math_doubleExtesnion_ToVector3.htm\u0000188","Vector3 构造函数 (Double[])\u0000html/M_Du_SolidWorks_Math_Vector3__ctor_1.htm\u0000114","Vector3.AngleD 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_AngleD.htm\u000033","MathPointExtension.Angle2D 方法\u0000html/M_Du_SolidWorks_Math_MathPointExtension_Angle2D.htm\u0000165","Vector3.AngleR 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_AngleR.htm\u000035","swEqu 属性\u0000html/Properties_T_Du_SolidWorks_Extension_swEqu.htm\u000051","SWCommandAttribute.Hint 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_Hint.htm\u000088","Vector3.Cross 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_Cross.htm\u000033","CustomPropertyModel.SwCustomInfoType 属性\u0000html/P_Du_SolidWorks_Extension_CustomPropertyModel_SwCustomInfoType.htm\u000073","SWPath 属性\u0000html/Properties_T_Du_SolidWorks_Extension_SWPath.htm\u000027","Vector3.Distance 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_Distance.htm\u000028","MathPointExtension.Project 方法\u0000html/M_Du_SolidWorks_Math_MathPointExtension_Project.htm\u0000272","SWCommandAttribute.ImageListIndex 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_ImageListIndex.htm\u000088","TestObj 属性\u0000html/Properties_T_Du_SolidWorks_Extension_TestObj.htm\u000025","CustomPropertyModel.Value 属性\u0000html/P_Du_SolidWorks_Extension_CustomPropertyModel_Value.htm\u000073","Vector3.DistanceSquared 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_DistanceSquared.htm\u000028","GroupData 属性\u0000html/Properties_T_Du_SolidWorks_GroupData.htm\u000028","Vector3.Dot 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_Dot.htm\u000033","SWCommandAttribute.MenuTBOption 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_MenuTBOption.htm\u000086","MathPointExtension.SubtractTs 方法 (IMathPoint, IMathPoint)\u0000html/M_Du_SolidWorks_Math_MathPointExtension_SubtractTs.htm\u0000244","Vector3.Set 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_Set.htm\u000031","SWCommandAttribute.Name 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_Name.htm\u000073","Vector3.UnitCross 方法\u0000html/Overload_Du_SolidWorks_Math_Vector3_UnitCross.htm\u000030","MathPointExtension.SubtractTs 方法 (IMathVector, IMathVector)\u0000html/M_Du_SolidWorks_Math_MathPointExtension_SubtractTs_1.htm\u0000244","SWCommandAttribute.Postion 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_Postion.htm\u000076","SWCommandAttribute.TextType 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_TextType.htm\u000079","MathPointExtension.ToVector3 方法\u0000html/M_Du_SolidWorks_Math_MathPointExtension_ToVector3.htm\u0000162","SWCommandAttribute.ToolTip 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_ToolTip.htm\u000073","IDuTaskPane 属性\u0000html/Properties_T_Du_SolidWorks_IDuTaskPane.htm\u000023","IFlyoutCommand 属性\u0000html/Properties_T_Du_SolidWorks_Interface_IFlyoutCommand.htm\u000025","MathUtilityExtension.PointEx 方法\u0000html/M_Du_SolidWorks_Math_MathUtilityExtension_PointEx.htm\u0000244","SWFlyoutCommandAttribute.Commands 属性\u0000html/P_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute_Commands.htm\u000094","ISolidWorksAddin 属性\u0000html/Properties_T_Du_SolidWorks_ISolidWorksAddin.htm\u000024","ISWAddinCommand 属性\u0000html/Properties_T_Du_SolidWorks_ISWAddinCommand.htm\u000024","MathUtilityExtension.ToSwMatrix 方法\u0000html/M_Du_SolidWorks_Math_MathUtilityExtension_ToSwMatrix.htm\u0000235","SWFlyoutCommandAttribute.FlyoutType 属性\u0000html/P_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute_FlyoutType.htm\u000088","ConvexHull2 属性\u0000html/Properties_T_Du_SolidWorks_Math_ConvexHull2.htm\u000026","MathUtil 属性\u0000html/Properties_T_Du_SolidWorks_Math_MathUtil.htm\u000024","SWFlyoutCommandAttribute.Guid 属性\u0000html/P_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute_Guid.htm\u000088","MathUtilityExtension.XAxis 方法\u0000html/M_Du_SolidWorks_Math_MathUtilityExtension_XAxis.htm\u0000182","PointDirection3 属性\u0000html/Properties_T_Du_SolidWorks_Math_PointDirection3.htm\u000025","SWFlyoutCommandAttribute.Hint 属性\u0000html/P_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute_Hint.htm\u000088","CustomPropertyModel.WasResloved 属性\u0000html/P_Du_SolidWorks_Extension_CustomPropertyModel_WasResloved.htm\u000073","Vector2 属性\u0000html/Properties_T_Du_SolidWorks_Math_Vector2.htm\u000032","SWFlyoutCommandAttribute.TextType 属性\u0000html/P_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute_TextType.htm\u000088","DuMacroFeatBase(TMacroFeature, TData).FeatureName 属性\u0000html/P_Du_SolidWorks_Extension_DuMacroFeatBase_2_FeatureName.htm\u000095","SWFlyoutCommandAttribute.Title 属性\u0000html/P_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute_Title.htm\u000088","Vector3 属性\u0000html/Properties_T_Du_SolidWorks_Math_Vector3.htm\u000044","ModelDocDuExtension.RayIntersection.IntersectionType 属性\u0000html/P_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection_IntersectionType.htm\u000088","DuMacroFeatBase(TMacroFeature, TData).FeatureOptions 属性\u0000html/P_Du_SolidWorks_Extension_DuMacroFeatBase_2_FeatureOptions.htm\u000095","SWFlyoutCommandAttribute.ToolTip 属性\u0000html/P_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute_ToolTip.htm\u000088","IPropertyManagerGroupBuilder.controls 属性\u0000html/P_Du_SolidWorks_Extension_IPropertyManagerGroupBuilder_controls.htm\u0000106","BoxOrderAttribute.Order 属性\u0000html/P_Du_SolidWorks_Attributes_BoxOrderAttribute_Order.htm\u000088","Edge3.A 属性\u0000html/P_Du_SolidWorks_Extension_Edge3_A.htm\u000088","CommandCollectionAttribute.Commands 属性\u0000html/P_Du_SolidWorks_Attributes_CommandCollectionAttribute_Commands.htm\u000094","CustomPropertyModel.EvalValue 属性\u0000html/P_Du_SolidWorks_Extension_CustomPropertyModel_EvalValue.htm\u000073","IPropertyManagerGroupBuilder.Group 属性\u0000html/P_Du_SolidWorks_Extension_IPropertyManagerGroupBuilder_Group.htm\u000085","Edge3.B 属性\u0000html/P_Du_SolidWorks_Extension_Edge3_B.htm\u000088","SWCommandAttribute.Guid 属性\u0000html/P_Du_SolidWorks_Attributes_SWCommandAttribute_Guid.htm\u000088","CustomPropertyModel.Name 属性\u0000html/P_Du_SolidWorks_Extension_CustomPropertyModel_Name.htm\u000073","IPropertyManagerPageWindowFromHandleWrapper.Height 属性\u0000html/P_Du_SolidWorks_Extension_IPropertyManagerPageWindowFromHandleWrapper_Height.htm\u000091","Edge3.Delta 属性\u0000html/P_Du_SolidWorks_Extension_Edge3_Delta.htm\u000088","Edge3 属性\u0000html/Properties_T_Du_SolidWorks_Extension_Edge3.htm\u000026","swEqu.Equation 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_Equation.htm\u000073","MacroFeatureDataExtension(TFeatComSerivce, TData).Data 属性\u0000html/P_Du_SolidWorks_Extension_MacroFeatureDataExtension_2_Data.htm\u000080","GroupData.Title 属性\u0000html/P_Du_SolidWorks_GroupData_Title.htm\u000085","FeatMgrFeatsNotFoundException 属性\u0000html/Properties_T_Du_SolidWorks_Extension_FeatMgrFeatsNotFoundException.htm\u000079","Vector2.Length 属性\u0000html/P_Du_SolidWorks_Math_Vector2_Length.htm\u000070","swEqu.GlobalVariable 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_GlobalVariable.htm\u000079","MacroFeatureDataExtension(TFeatComSerivce, TData).FeatName 属性\u0000html/P_Du_SolidWorks_Extension_MacroFeatureDataExtension_2_FeatName.htm\u000082","IPropertyManagerGroupBuilder 属性\u0000html/Properties_T_Du_SolidWorks_Extension_IPropertyManagerGroupBuilder.htm\u000025","GroupData.ToolTip 属性\u0000html/P_Du_SolidWorks_GroupData_ToolTip.htm\u000085","Vector2.LengthSquared 属性\u0000html/P_Du_SolidWorks_Math_Vector2_LengthSquared.htm\u000070","swEqu.Index 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_Index.htm\u000073","IDuTaskPane.UI 属性\u0000html/P_Du_SolidWorks_IDuTaskPane_UI.htm\u000080","MacroFeatureDataExtension(TFeatComSerivce, TData).ServicePath 属性\u0000html/P_Du_SolidWorks_Extension_MacroFeatureDataExtension_2_ServicePath.htm\u000077","Vector2.X 属性\u0000html/P_Du_SolidWorks_Math_Vector2_X.htm\u000088","swEqu.Remark 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_Remark.htm\u000088","IFlyoutCommand.FlyoutCMDId 属性\u0000html/P_Du_SolidWorks_Interface_IFlyoutCommand_FlyoutCMDId.htm\u000086","ModelDocDuExtension.RayIntersection.Body 属性\u0000html/P_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection_Body.htm\u000088","Vector2.XPlusVector 属性\u0000html/P_Du_SolidWorks_Math_Vector2_XPlusVector.htm\u000087","swEqu.Status 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_Status.htm\u000073","IFlyoutCommand.FlyoutGroup 属性\u0000html/P_Du_SolidWorks_Interface_IFlyoutCommand_FlyoutGroup.htm\u000086","ModelDocDuExtension.RayIntersection.HitPoint 属性\u0000html/P_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection_HitPoint.htm\u000088","Vector2.Y 属性\u0000html/P_Du_SolidWorks_Math_Vector2_Y.htm\u000088","swEqu.Suppression 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_Suppression.htm\u000073","ISolidWorksAddin.SwApp 属性\u0000html/P_Du_SolidWorks_ISolidWorksAddin_SwApp.htm\u000080","Vector2.Zero 属性\u0000html/P_Du_SolidWorks_Math_Vector2_Zero.htm\u000087","swEqu.Value 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_Value.htm\u000075","ISolidWorksAddin.swMath 属性\u0000html/P_Du_SolidWorks_ISolidWorksAddin_swMath.htm\u000080","Vector3.Abs 属性\u0000html/P_Du_SolidWorks_Math_Vector3_Abs.htm\u000085","swEqu.VarName 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_VarName.htm\u000084","ISWAddinCommand.CmdGroupIDs 属性\u0000html/P_Du_SolidWorks_ISWAddinCommand_CmdGroupIDs.htm\u000095","Vector3.IsFinite 属性\u0000html/P_Du_SolidWorks_Math_Vector3_IsFinite.htm\u000085","swEqu.VarValue 属性\u0000html/P_Du_SolidWorks_Extension_swEqu_VarValue.htm\u000096","ISWAddinCommand.CommandInstances 属性\u0000html/P_Du_SolidWorks_ISWAddinCommand_CommandInstances.htm\u0000104","SWPath.ExtensionDllPath 属性\u0000html/P_Du_SolidWorks_Extension_SWPath_ExtensionDllPath.htm\u000074","Vector3.IsNormalized 属性\u0000html/P_Du_SolidWorks_Math_Vector3_IsNormalized.htm\u000085","ConvexHull2.mE 属性\u0000html/P_Du_SolidWorks_Math_ConvexHull2_mE.htm\u000088","TestObj.Name 属性\u0000html/P_Du_SolidWorks_Extension_TestObj_Name.htm\u000088","Vector3.Length 属性\u0000html/P_Du_SolidWorks_Math_Vector3_Length.htm\u000085","ConvexHull2.MinYVectorIndex 属性\u0000html/P_Du_SolidWorks_Math_ConvexHull2_MinYVectorIndex.htm\u000085","PMPageControl.ID 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControl_ID.htm\u000088","Vector3.LengthL1 属性\u0000html/P_Du_SolidWorks_Math_Vector3_LengthL1.htm\u000070","TestObj.Selections 属性\u0000html/P_Du_SolidWorks_Extension_TestObj_Selections.htm\u0000100","ConvexHull2.mVectors 属性\u0000html/P_Du_SolidWorks_Math_ConvexHull2_mVectors.htm\u0000100","PMPageControl.Options 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControl_Options.htm\u000088","Vector3.LengthSquared 属性\u0000html/P_Du_SolidWorks_Math_Vector3_LengthSquared.htm\u000085","GroupData.Hint 属性\u0000html/P_Du_SolidWorks_GroupData_Hint.htm\u000085","MathUtil.swMathUtility 属性\u0000html/P_Du_SolidWorks_Math_MathUtil_swMathUtility.htm\u000090","PMPageControl.PMPageObject 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControl_PMPageObject.htm\u000088","Vector3.Max 属性\u0000html/P_Du_SolidWorks_Math_Vector3_Max.htm\u000085","GroupData.IconAssembly 属性\u0000html/P_Du_SolidWorks_GroupData_IconAssembly.htm\u000085","PointDirection3.Direction 属性\u0000html/P_Du_SolidWorks_Math_PointDirection3_Direction.htm\u000088","PMPageControl.tip 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControl_tip.htm\u000088","Vector3.MaxAbs 属性\u0000html/P_Du_SolidWorks_Math_Vector3_MaxAbs.htm\u000085","GroupData.Icons 属性\u0000html/P_Du_SolidWorks_GroupData_Icons.htm\u000091","PointDirection3.Point 属性\u0000html/P_Du_SolidWorks_Math_PointDirection3_Point.htm\u000088","Range3Double.Corner1 属性\u0000html/P_Du_SolidWorks_Extension_Range3Double_Corner1.htm\u000075","IPropertyManagerPageWindowFromHandleWrapper 属性\u0000html/Properties_T_Du_SolidWorks_Extension_IPropertyManagerPageWindowFromHandleWrapper.htm\u000024","GroupData.TabStyles 属性\u0000html/P_Du_SolidWorks_GroupData_TabStyles.htm\u000091","Vector3.Min 属性\u0000html/P_Du_SolidWorks_Math_Vector3_Min.htm\u000085","Vector2.IsFinite 属性\u0000html/P_Du_SolidWorks_Math_Vector2_IsFinite.htm\u000085","Range3Double.Corner2 属性\u0000html/P_Du_SolidWorks_Extension_Range3Double_Corner2.htm\u000076","MacroFeatureDataExtension(TFeatComSerivce, TData) 属性\u0000html/Properties_T_Du_SolidWorks_Extension_MacroFeatureDataExtension_2.htm\u000039","Vector3.MinAbs 属性\u0000html/P_Du_SolidWorks_Math_Vector3_MinAbs.htm\u000085","RayIntersection 属性\u0000html/Properties_T_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection.htm\u000030","SelectionBoxAttribute.Fileter 属性\u0000html/P_Du_SolidWorks_Extension_SelectionBoxAttribute_Fileter.htm\u000091","IFeatureExtension 类\u0000html/T_Du_SolidWorks_Extension_IFeatureExtension.htm\u000092","ObjectId 属性\u0000html/Properties_T_Du_SolidWorks_Extension_ObjectId.htm\u000028","SelectionBoxAttribute.Height 属性\u0000html/P_Du_SolidWorks_Extension_SelectionBoxAttribute_Height.htm\u000085","ObjectSelection 类\u0000html/T_Du_SolidWorks_Extension_ObjectSelection.htm\u0000163","SelectionManagerExtensions 类\u0000html/T_Du_SolidWorks_Extension_SelectionManagerExtensions.htm\u0000106","ObjectSelection 属性\u0000html/Properties_T_Du_SolidWorks_Extension_ObjectSelection.htm\u000031","IMacroFeatureDataExtension 类\u0000html/T_Du_SolidWorks_Extension_IMacroFeatureDataExtension.htm\u0000110","OperationsResult 属性\u0000html/Properties_T_Du_SolidWorks_Extension_OperationsResult.htm\u000047","SelectionData.ObjectIds 属性\u0000html/P_Du_SolidWorks_Extension_SelectionData_ObjectIds.htm\u0000100","PMPageControl 属性\u0000html/Properties_T_Du_SolidWorks_Extension_PMPageControl.htm\u000030","SurfaceExtensions.PointUv.Point 属性\u0000html/P_Du_SolidWorks_Extension_SurfaceExtensions_PointUv_Point.htm\u000094","OperationsResult 类\u0000html/T_Du_SolidWorks_Extension_OperationsResult.htm\u0000167","PMPageControlAttribute 属性\u0000html/Properties_T_Du_SolidWorks_Extension_PMPageControlAttribute.htm\u000032","SurfaceExtensions.PointUv.U 属性\u0000html/P_Du_SolidWorks_Extension_SurfaceExtensions_PointUv_U.htm\u000088","IFlyoutCommand 接口\u0000html/T_Du_SolidWorks_Interface_IFlyoutCommand.htm\u000080","IPropertyManagerGroupBuilder 类\u0000html/T_Du_SolidWorks_Extension_IPropertyManagerGroupBuilder.htm\u0000157","Range3Double 属性\u0000html/Properties_T_Du_SolidWorks_Extension_Range3Double.htm\u000032","ModelDocDuExtension.RayIntersection.Normals 属性\u0000html/P_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection_Normals.htm\u000088","ISolidWorksAddin 接口\u0000html/T_Du_SolidWorks_ISolidWorksAddin.htm\u000072","RefAxisNotFoundException 属性\u0000html/Properties_T_Du_SolidWorks_Extension_RefAxisNotFoundException.htm\u000079","PMPageControl 类\u0000html/T_Du_SolidWorks_Extension_PMPageControl.htm\u0000178","SelectionBoxAttribute 属性\u0000html/Properties_T_Du_SolidWorks_Extension_SelectionBoxAttribute.htm\u000032","ModelDocDuExtension.RayIntersection.RayIndex 属性\u0000html/P_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection_RayIndex.htm\u000088","SurfaceExtensions.PointUv.UV 属性\u0000html/P_Du_SolidWorks_Extension_SurfaceExtensions_PointUv_UV.htm\u000094","ISWAddinCommand 接口\u0000html/T_Du_SolidWorks_ISWAddinCommand.htm\u000079","IPropertyManagerPage2Builder 类\u0000html/T_Du_SolidWorks_Extension_IPropertyManagerPage2Builder.htm\u0000161","ObjectId.Data 属性\u0000html/P_Du_SolidWorks_Extension_ObjectId_Data.htm\u000084","SurfaceExtensions.PointUv.V 属性\u0000html/P_Du_SolidWorks_Extension_SurfaceExtensions_PointUv_V.htm\u000088","PMPageControlAttribute 类\u0000html/T_Du_SolidWorks_Extension_PMPageControlAttribute.htm\u0000169","ObjectId.SelectionType 属性\u0000html/P_Du_SolidWorks_Extension_ObjectId_SelectionType.htm\u000088","SurfaceExtensions.PointUv.X 属性\u0000html/P_Du_SolidWorks_Extension_SurfaceExtensions_PointUv_X.htm\u000088","IPropertyManagerPageSelectionboxExtension 类\u0000html/T_Du_SolidWorks_Extension_IPropertyManagerPageSelectionboxExtension.htm\u000092","ConvexHull2 类\u0000html/T_Du_SolidWorks_Math_ConvexHull2.htm\u0000158","ObjectSelection.Index 属性\u0000html/P_Du_SolidWorks_Extension_ObjectSelection_Index.htm\u000070","SurfaceExtensions.PointUv.Y 属性\u0000html/P_Du_SolidWorks_Extension_SurfaceExtensions_PointUv_Y.htm\u000088","doubleExtesnion 类\u0000html/T_Du_SolidWorks_Math_doubleExtesnion.htm\u000088","ObjectSelection.Mark 属性\u0000html/P_Du_SolidWorks_Extension_ObjectSelection_Mark.htm\u000070","PointParam 类\u0000html/T_Du_SolidWorks_Extension_PointParam.htm\u0000155","SurfaceExtensions.PointUv.Z 属性\u0000html/P_Du_SolidWorks_Extension_SurfaceExtensions_PointUv_Z.htm\u000088","IPropertyManagerPageWindowFromHandleWrapper 类\u0000html/T_Du_SolidWorks_Extension_IPropertyManagerPageWindowFromHandleWrapper.htm\u0000161","ObjectSelection.Object 属性\u0000html/P_Du_SolidWorks_Extension_ObjectSelection_Object.htm\u000073","PropertyManagerPage2Extension 类\u0000html/T_Du_SolidWorks_Extension_PropertyManagerPage2Extension.htm\u000089","MathPointExtension 类\u0000html/T_Du_SolidWorks_Math_MathPointExtension.htm\u0000106","Vector3.UnitX 属性\u0000html/P_Du_SolidWorks_Math_Vector3_UnitX.htm\u000087","ObjectSelection.Type 属性\u0000html/P_Du_SolidWorks_Extension_ObjectSelection_Type.htm\u000070","Vector3.UnitY 属性\u0000html/P_Du_SolidWorks_Math_Vector3_UnitY.htm\u000087","SelectionData 属性\u0000html/Properties_T_Du_SolidWorks_Extension_SelectionData.htm\u000024","Vector3.UnitZ 属性\u0000html/P_Du_SolidWorks_Math_Vector3_UnitZ.htm\u000087","MacroFeatureDataExtension(TFeatComSerivce, TData) 类\u0000html/T_Du_SolidWorks_Extension_MacroFeatureDataExtension_2.htm\u0000235","MathUtil 类\u0000html/T_Du_SolidWorks_Math_MathUtil.htm\u0000163","PointUv 属性\u0000html/Properties_T_Du_SolidWorks_Extension_SurfaceExtensions_PointUv.htm\u000032","Vector3.X 属性\u0000html/P_Du_SolidWorks_Math_Vector3_X.htm\u000088","SldWorksExtension 类\u0000html/T_Du_SolidWorks_Extension_SldWorksExtension.htm\u0000153","MathUtilityExtension 类\u0000html/T_Du_SolidWorks_Math_MathUtilityExtension.htm\u000092","PropertyManagerPage2Handler9Wrapper 类\u0000html/T_Du_SolidWorks_Extension_PropertyManagerPage2Handler9Wrapper.htm\u0000289","Vector3.xy 属性\u0000html/P_Du_SolidWorks_Math_Vector3_xy.htm\u000088","ManipulatorHandler 类\u0000html/T_Du_SolidWorks_Extension_ManipulatorHandler.htm\u0000171","StateEnum 枚举\u0000html/T_Du_SolidWorks_Extension_StateEnum.htm\u000074","Vector3.xz 属性\u0000html/P_Du_SolidWorks_Math_Vector3_xz.htm\u000088","MathVectorExtension 类\u0000html/T_Du_SolidWorks_Math_MathVectorExtension.htm\u0000112","MateAlignExtension 枚举\u0000html/T_Du_SolidWorks_Extension_MateAlignExtension.htm\u000076","Vector3.Y 属性\u0000html/P_Du_SolidWorks_Math_Vector3_Y.htm\u000088","OperationsResult.Bodies 属性\u0000html/P_Du_SolidWorks_Extension_OperationsResult_Bodies.htm\u000090","PropertyManagerPageGroupExtension 类\u0000html/T_Du_SolidWorks_Extension_PropertyManagerPageGroupExtension.htm\u0000113","SurfaceExtensions 类\u0000html/T_Du_SolidWorks_Extension_SurfaceExtensions.htm\u0000115","Vector3.yz 属性\u0000html/P_Du_SolidWorks_Math_Vector3_yz.htm\u000088","PointDirection3 类\u0000html/T_Du_SolidWorks_Math_PointDirection3.htm\u0000156","OperationsResult.Error 属性\u0000html/P_Du_SolidWorks_Extension_OperationsResult_Error.htm\u000076","Vector3.Z 属性\u0000html/P_Du_SolidWorks_Math_Vector3_Z.htm\u000088","Range3Double 类\u0000html/T_Du_SolidWorks_Extension_Range3Double.htm\u0000162","PMPageControlAttribute.Caption 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControlAttribute_Caption.htm\u000085","SurfaceExtensions.PointUv 类\u0000html/T_Du_SolidWorks_Extension_SurfaceExtensions_PointUv.htm\u0000167","Vector3.Zero 属性\u0000html/P_Du_SolidWorks_Math_Vector3_Zero.htm\u000087","PMPageControlAttribute.Tip 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControlAttribute_Tip.htm\u000085","RefAxisExtension 类\u0000html/T_Du_SolidWorks_Extension_RefAxisExtension.htm\u000088","Vector2 类\u0000html/T_Du_SolidWorks_Math_Vector2.htm\u0000212","PMPageControl.Align 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControl_Align.htm\u000088","SwCalloutHandlerWrapper 类\u0000html/T_Du_SolidWorks_Extension_SwCalloutHandlerWrapper.htm\u0000161","BoxOrderAttribute 类\u0000html/T_Du_SolidWorks_Attributes_BoxOrderAttribute.htm\u0000168","PMPageControl.Caption 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControl_Caption.htm\u000088","PMPageControl.ControlType 属性\u0000html/P_Du_SolidWorks_Extension_PMPageControl_ControlType.htm\u000088","MathTransformExtension 类\u0000html/T_Du_SolidWorks_Extension_MathTransformExtension.htm\u000096","Vector3 类\u0000html/T_Du_SolidWorks_Math_Vector3.htm\u0000287","SwCalloutHandlerWrapperHelper 类\u0000html/T_Du_SolidWorks_Extension_SwCalloutHandlerWrapperHelper.htm\u0000141","CommandCollectionAttribute 类\u0000html/T_Du_SolidWorks_Attributes_CommandCollectionAttribute.htm\u0000168","Matrix4X4ExtensionsSw 类\u0000html/T_Du_SolidWorks_Extension_Matrix4X4ExtensionsSw.htm\u000088","RefAxisNotFoundException 类\u0000html/T_Du_SolidWorks_Extension_RefAxisNotFoundException.htm\u0000227","RefPlaneExtesion 类\u0000html/T_Du_SolidWorks_Extension_RefPlaneExtesion.htm\u000093","SWCommandAttribute 类\u0000html/T_Du_SolidWorks_Attributes_SWCommandAttribute.htm\u0000207","swEqu 类\u0000html/T_Du_SolidWorks_Extension_swEqu.htm\u0000192","ModelDocDuExtension 类\u0000html/T_Du_SolidWorks_Extension_ModelDocDuExtension.htm\u0000301","SelectionBoxAttribute 类\u0000html/T_Du_SolidWorks_Extension_SelectionBoxAttribute.htm\u0000182","SWFlyoutCommandAttribute 类\u0000html/T_Du_SolidWorks_Attributes_SWFlyoutCommandAttribute.htm\u0000188","SWFile 类\u0000html/T_Du_SolidWorks_Extension_SWFile.htm\u0000164","ModelDocDuExtension.EquationsDimensionType 枚举\u0000html/T_Du_SolidWorks_Extension_ModelDocDuExtension_EquationsDimensionType.htm\u000063","SelectionBoxExtensions 类\u0000html/T_Du_SolidWorks_Extension_SelectionBoxExtensions.htm\u000088","CommandType 枚举\u0000html/T_Du_SolidWorks_CommandType.htm\u000071","ModelDocDuExtension.RayIntersection 类\u0000html/T_Du_SolidWorks_Extension_ModelDocDuExtension_RayIntersection.htm\u0000149","SWPath 类\u0000html/T_Du_SolidWorks_Extension_SWPath.htm\u0000176","ComWrapper 类\u0000html/T_Du_SolidWorks_ComWrapper.htm\u0000143","SelectionData 类\u0000html/T_Du_SolidWorks_Extension_SelectionData.htm\u0000225","ModelerExtension 类\u0000html/T_Du_SolidWorks_Extension_ModelerExtension.htm\u0000149","SelectionDataExtension 类\u0000html/T_Du_SolidWorks_Extension_SelectionDataExtension.htm\u0000157","AssemblyDocExtension 类\u0000html/T_Du_SolidWorks_Extension_AssemblyDocExtension.htm\u0000133","ObjectId 类\u0000html/T_Du_SolidWorks_Extension_ObjectId.htm\u0000144","BodyExtension 类\u0000html/T_Du_SolidWorks_Extension_BodyExtension.htm\u0000112","swSelectTypeName 类\u0000html/T_Du_SolidWorks_Extension_swSelectTypeName.htm\u0000334","Component2Extension 类\u0000html/T_Du_SolidWorks_Extension_Component2Extension.htm\u0000128","TestObj 类\u0000html/T_Du_SolidWorks_Extension_TestObj.htm\u0000155","TriadManipulatorExtensions 类\u0000html/T_Du_SolidWorks_Extension_TriadManipulatorExtensions.htm\u000089","CustomPropertyManagerExtension 类\u0000html/T_Du_SolidWorks_Extension_CustomPropertyManagerExtension.htm\u0000125","ViewExtension 类\u0000html/T_Du_SolidWorks_Extension_ViewExtension.htm\u000095","CustomPropertyModel 类\u0000html/T_Du_SolidWorks_Extension_CustomPropertyModel.htm\u0000163","GroupData 结构\u0000html/T_Du_SolidWorks_GroupData.htm\u0000127","IDuTaskPane 接口\u0000html/T_Du_SolidWorks_IDuTaskPane.htm\u000071","Delat 类\u0000html/T_Du_SolidWorks_Extension_Delat.htm\u0000156","DuMacroFeatBase(TMacroFeature, TData) 类\u0000html/T_Du_SolidWorks_Extension_DuMacroFeatBase_2.htm\u0000280","Edge3 类\u0000html/T_Du_SolidWorks_Extension_Edge3.htm\u0000156","EdgeExtension 类\u0000html/T_Du_SolidWorks_Extension_EdgeExtension.htm\u000091","EnumObjExtension 类\u0000html/T_Du_SolidWorks_Extension_EnumObjExtension.htm\u000090","EquationManagerExtension 类\u0000html/T_Du_SolidWorks_Extension_EquationManagerExtension.htm\u0000120","FaceExtension 类\u0000html/T_Du_SolidWorks_Extension_FaceExtension.htm\u000093","FeatMgrFeatsNotFoundException 类\u0000html/T_Du_SolidWorks_Extension_FeatMgrFeatsNotFoundException.htm\u0000241","FeatureManagerExtension 类\u0000html/T_Du_SolidWorks_Extension_FeatureManagerExtension.htm\u000079","FeatureTypeName 类\u0000html/T_Du_SolidWorks_Extension_FeatureTypeName.htm\u0000212","ICurveExtension 类\u0000html/T_Du_SolidWorks_Extension_ICurveExtension.htm\u0000102"]